### ISSUE TITLE
csetuid Chinese UID0 writable

### ISSUE THREAD

**Issue by Amurmurmur** [ikarus23/MifareClassicTool#102]
Hi there,
just wondering if there is anyway to set UID with MCT for Chinese Block0 writable mifare cards?

Is there anyway in general to do it on android without Proxmark3 (like mf csetuid command)

**Comment by ikarus23** [comment]
From the readme:
>The first block of the first sector of an original MIFARE Classic tag is read-only i.e. not writable. But there are special MIFARE Classic tags that support writing to the manufacturer block with a simple write command. This App is able to write to such tags and can therefore create fully correct clones. However, some special tags require a special command sequence to put them into the state where writing to the manufacturer block is possible. These tags will not work.
Remember this when you are shopping for special tags!

You can't write the UID of tags that use the special command. This is simply not possible with Android. You don't need a Proxmark3, but you will need an additional reader (e.g. ACR 122u).
