### ISSUE TITLE
Add working with Mifare Plus 2K

### ISSUE THREAD

**Issue by user314** [ikarus23/MifareClassicTool#104]
When I try to read mifare plus 2k card using MifareClassicTool app reads only 16 sectors (64 blocks), but the card consist of 128 blocks (32 sectors)
This card Mifare Plus 2K

Reading on pc:
$ nfc-mfclassic r a dump.bin keys.bin
NFC reader: ACS / ACR122U PICC Interface opened
Found MIFARE Classic card:
ISO/IEC 14443A (106 kbps) target:
    ATQA (SENS_RES): 00  44  
       UID (NFCID1): 04  05  40  0a  be  4c  80  
      SAK (SEL_RES): 08  
Guessing size: seems to be a 2048-byte card
Reading out 128 blocks |................................................................................................................................|
Done, 128 of 128 blocks read.
Writing data to file: dump.bin ...Done.

MIFARE Type Identification Procedure
[http://cache.nxp.com/documents/application_note/AN10833.pdf](url)

**Comment by ikarus23** [comment]
Hi,
Android is not capable of detecting MIFARE Plus 2k tags (in MIFARE Classic compatibility mode). However, if you are using the latest version of MCT you can specify the sector count and ignore the sector count detected by Android. Just go to MCT's options and specify a sector count of 32.
