### ISSUE TITLE
Pasword Protected MIFARE Classic 1K Card Memory

### ISSUE THREAD

**Issue by thanthdinesh** [ikarus23/MifareClassicTool#112]
Can We Write Protected MIFARE Classic 1K Card Memory ??
MIFARE Classic 1K Card Memory can be readable and writable only by me.Is it possible to Protected by password ??

**Comment by ikarus23** [comment]
I'm not sure if I understand your issue correctly...
You can write a MIFARE Classic card as long as you have the correct key (A or B) and the Access Conditions match. Only people with the right key are able to write to the tag. So it's kind of a password. However, there are tools out there to crack MIFARE Classic keys. If you really want to protect the data of an MIFARE Classic card you have to apply your own layer of encryption/signing.

**Comment by ikarus23** [comment]
There are no such things like passwords for MIFARE Classic. Only the two keys. There is no other protection mechanism. And yes, you can make a tag read only.

**Comment by ikarus23** [comment]
Old and OT. Closed.
