### ISSUE TITLE
MCT equivalent for Windows/Linux ?

### ISSUE THREAD

**Issue by juancols** [ikarus23/MifareClassicTool#116]
Hello everyone,

I'm using the [Adafruit PN532 breakout](https://www.adafruit.com/product/364) together with a [USB/Serial converter](https://www.sparkfun.com/products/11812) for interfacing with my MIFARE Classic 1k and getting the keys. Unfortunately, my Nexus 5 doesn't support the PN532 chip and I can't use MCT.

Is there a similar project to Mifare Classic Tool but for Windows or Linux? I've spent my last couple of days rummaging everywhere but I haven't found anything so far. 

Thanks!

**Comment by osysltd** [comment]
Try mfterm, quite nice functionality and possibilities

**Comment by juancols** [comment]
Thank you! It looks promising.

**Comment by ikarus23** [comment]
Old issue. Closed.
