### ISSUE TITLE
Random UID

### ISSUE THREAD

**Issue by maxben14** [ikarus23/MifareClassicTool#121]
I want to edit code in apk. I want that apk write random uid. Please, say me name of function which write manufactor block 0 in mifare classic ?

**Comment by ikarus23** [comment]
You just have to create an instance of the [MCReader](https://github.com/ikarus23/MifareClassicTool/blob/master/Mifare%20Classic%20Tool/app/src/main/java/de/syss/MifareClassicTool/MCReader.java) and use the [writeBlock()](https://github.com/ikarus23/MifareClassicTool/blob/master/Mifare%20Classic%20Tool/app/src/main/java/de/syss/MifareClassicTool/MCReader.java#L401) function. But be carefull with random UIDs. The BCC has to match!
