### ISSUE TITLE
Samsung Galaxy S7 Edge compatible. Android 7.0

### ISSUE THREAD

**Issue by rjsilvestre** [ikarus23/MifareClassicTool#125]
Although listed as incompatible and not able to install from Play store I installed the APK and the MCT works perfectly.
Maybe the model could be delisted.

Thanks!

**Comment by ikarus23** [comment]
Hi @rjsilvestre, thank you for reporting this. What exact model do you have?

**Comment by rjsilvestre** [comment]
@ikarus23 the model is SM-G9350
Tell me if you need any other information.

**Comment by ikarus23** [comment]
Thanks, but unfortunately google does not list the device with this name.
There are the following S7 Edge devices available: 
```
SamsungGalaxy S7 Edge– SCV33
SamsungGalaxy S7 Edge– hero2qltecctvzw
SamsungGalaxy S7 Edge– hero2lte
SamsungGalaxy S7 Edge– hero2qltespr
SamsungGalaxy S7 Edge– hero2ltelgt
SamsungGalaxy S7 Edge– hero2lteskt
SamsungGalaxy S7 Edge– hero2qltetmo
SamsungGalaxy S7 Edge– SC-02H
SamsungGalaxy S7 Edge– hero2qltechn
SamsungGalaxy S7 Edge– hero2qlteue
SamsungGalaxy S7 Edge– hero2qlteusc
SamsungGalaxy S7 Edge– hero2qlteatt
SamsungGalaxy S7 Edge– hero2qltevzw
SamsungGalaxy S7 Edge– hero2ltebmc
SamsungGalaxy S7 Edge– hero2ltektt
```
Do you know which one of these could be your device?

**Comment by rjsilvestre** [comment]
hero2qltechn
Had to check on AIDA64
Thanks!

**Comment by ikarus23** [comment]
Thanks! I will update the list and remove the device from the black list in Google Play.

**Comment by ikarus23** [comment]
Updated List too in 9cca1ca807ccaf434e28b05f9179f87f9bc2201f.
