### ISSUE TITLE
connect external reader

### ISSUE THREAD

**Issue by kyo87** [ikarus23/MifareClassicTool#13]
Hi,

I have Samsung Galaxy SII (without NFC module)
I have external card reader (ACR122U) connected via USB. Reader in represented in system on /dev/bus/usb/002/002 and working fine in other aplications.
I would like to use MifareClassicTool because I heared that this is the best app for reading/writing data.

Can I bypass error message when MCT starts? I use MCT in newest  version (1.7.2). Maybe some older version haven't that message? 

Maybe can you add a feature, that supports external devices?

Please help me. 
Best regards,
Kris

ACR122U Drivers for android:
http://www.acs.com.hk/en/driver/3/acr122u-usb-nfc-reader/

**Comment by diegoespindola** [comment]
Hi, great app, but i also have nexus 5 and a acr122u external reader, are you planing to add this new feature soon or you dont want to?

**Comment by ikarus23** [comment]
Hi there,
thank you. Yes, I still want to implement a feature like this. But I don't think it will be soon. Although my last update on this topic is from a year ago, I'm still really low on spare time to work on MCT.

**Comment by zero800** [comment]
Waiting for acr122u external reader support :)

**Comment by DRSDavidSoft** [comment]
@ikarus23, did you have any time to work on ACR122U support? I'm willing to contribute to the project if you can guide me on how to get started.

**Comment by ikarus23** [comment]
@DRSDavidSoft, there is a test build over at https://github.com/ikarus23/MifareClassicTool/issues/123 (testing8). You need to install External NFC for this.

**Comment by ikarus23** [comment]
This feature has been released with version 2.2.0 (a44921d5156996d0a6ed1d7e8469fe7a5daefb67).
I tested it with and ACR 122U and it worked for me (in most cases). [External NFC](https://play.google.com/store/apps/details?id=eu.dedb.nfc.service) has to be installed.
