### ISSUE TITLE
No valid key found in choosen key file [2]

### ISSUE THREAD

**Issue by Johkg011** [ikarus23/MifareClassicTool#135]
Hello friend, please help me
I'm cloning a Mifare card, I've used LibNfc and found all the keys. I added them in the MCT Apk and I was able to read the card completely, but at the time of cloning the sectors this error appears .. sectors 1 to 15 were identical, but in sector 0 the KEY B is thus "------ ------ "and with that, Block 0 of this sector is also dashed, I can not clone these sectors 
Please help me
My phone is a Motorola Razr D3
I await an answer

**Comment by ikarus23** [comment]
I'm not sure if I understood everything.
1. You "found" all keys with libnfc
2. You were able to read the whole tag with MCT (no dashes anywhere)
3. Sector 1 to 15 were all the same
4. After writing, KeyB of sector 0 is unknown
5. After writing block 0 (of sector 0) is unknown

Right?
What keys did you found? Only "000000000000" and "FFFFFFFFFFFFFF"? What keys are in the file you want to write? Could you give an example?

**Comment by Johkg011** [comment]
Exactly.
The keys I found were these:

C620318EF179
8553263F4FF0
0A7932DC7E65
11428B5BCE06
11428B5BCE07
11428B5BCE08
11428B5BCE09
11428B5BCE0A
11428B5BCE0F
18971D893494
44F0B5FBE344
25D60050BF6E
E241E8AFCBAF
8E5D33A6ED51
9F42971E8322
D4FE03CE5B06
D4FE03CE5B07
D4FE03CE5B08
D4FE03CE5B09
D4FE03CE5B0A
25D60050BF6E
E241E8AFCBAF
8E5D33A6ED51
9F42971E8322
7B296F353C6B
3FA7217EC575
D4FE03CE5B0F

The key B of Sector 0 is that 18971D893494, when I read the original card it appears, but when I try to clone that error appears. I already tried to write only Sector 0 and I also could not.

**Comment by ikarus23** [comment]
What are the access conditions (part between the keys) of sector 0?

**Comment by Johkg011** [comment]
AC's sector 0 = E69871CB

I could see that the Value Block is Sector 0.
Will there be any hidden key that is responsible for the recording?

**Comment by Johkg011** [comment]
Friend, I tried to record using a Samsung Galaxy S5 and the problem was the same.
I did the normal reading, but at the time of writing Key B of Sector 0 was "-----", I still checked the option "Advanced: save manufacturer block" but also did not solve.
Please help me

**Comment by ikarus23** [comment]
Could you give a full example? (sector 0 should be enough)
* The tag before writing
* The dump you want to write
* The result after writing

**Comment by Johkg011** [comment]
I'm cloning a transport card, an original sticker is this:

0195EEDBA18804004323C41000070A0D
ADFDFF7F52020080ADFDFF7F00FF00FF
ADFDFF7F52020080ADFDFF7F00FF00FF
7B296F353C6BE69871CB18971D893494

This is sector 0 of the s50 1k card uid changeable:


A0B115EEEA0804000000000000000000
00000000000000000000000000000000
00000000000000000000000000000000
FFFFFFFFFFFFFF078069FFFFFFFFFFFF

This is the result after the recording:

--------------------------------
ADFDFF7F52020080ADFDFF7F00FF00FF
ADFDFF7F52020080ADFDFF7F00FF00FF
7B296F353C6BE69871CB------------

**Comment by Johkg011** [comment]
The key B and block 0 of this sector are thus "-----"

**Comment by ikarus23** [comment]
Ok, so far I have no clue what is causing this. It might be an issue with the block 0 writable tag. Have you tied [this testing version of MCT](http://tests.icaria.de/MifareClassicTool-2.1.0-testing5.apk)?

**Comment by Johkg011** [comment]
The problem has been resolved friend.
I had to change the access condition through the hexadecimal calculator.
From E69871 I moved to 19678E, the recording of Block 0 worked.
Thank you.

**Comment by ikarus23** [comment]
Oh, ok. Well, if it works now I'm closing this.

**Comment by trustedman** [comment]
Hello guys.. 

Can help me pls ? https://github.com/trustedman/Mifare-Classic-1k---Money-Read-HELP-ME/issues/1

![WhatsApp Image 2020-11-23 at 12 07 13](https://user-images.githubusercontent.com/56659345/100105899-a245bd80-2e46-11eb-903d-c3772d6d4268.jpeg)

![WhatsApp Image 2020-11-22 at 09 59 50](https://user-images.githubusercontent.com/56659345/100105904-a2de5400-2e46-11eb-8d87-eb6d5245cd32.jpeg)

**Comment by ikarus23** [comment]
Please don't spam a random issue.
I've replied to your issue.
