### ISSUE TITLE
[Feature] Mifare emulation and key recovery

### ISSUE THREAD

**Issue by gmkbenjamin** [ikarus23/MifareClassicTool#136]
Dear author,
Is it possible to add the below features?
1. Key recovery like mfoc and mfcuk (without using external USB readers)? 
2. Is emulation possible? I know that UID will be randomly generated each time it's read due to Android limitation. But what about other sectors?

**Comment by ikarus23** [comment]
Hello @gmkbenjamin, sorry, but it is not possible to implement these features.
1. It is not possible to control the NFC controller with Android in the way it is needed to do key recovery.
2. It is not possible to emulate Mifare Classic tags with Android at all.

**Comment by ArchangeGabriel** [comment]
Doesn’t it depend on the driver/chip?

**Comment by ikarus23** [comment]
Well, of course you can do both of these things if you have the right chip and the right driver. But the official Android does not ship with drivers that powerful. If we are talking about custom ROMs it should be possible. But I cant't do this things within the code of MCT.

**Comment by gmkbenjamin** [comment]
I thought host based card emulation would allow you to emulate ISO/IEC 14443-3 cards. 
https://www.mifare.net/support/forum/topic/creating-nfc-android-app-to-act-as-mifare-card-to-interact-with-mifare-readers/

I will do more digging.

**Comment by ikarus23** [comment]
Yes, but Mifare Classic is not compatible with ISO/IEC 14443-3. Only in the anti-collision and selection phase at the very beginning of the communication.

**Comment by gmkbenjamin** [comment]
Ah right seems like everything points to driver modification. Thank you for your answer.
