### ISSUE TITLE
Moto X 2nd Gen - App does not open

### ISSUE THREAD

**Issue by dellagustin** [ikarus23/MifareClassicTool#138]
I have the following phone:
http://www.gsmarena.com/motorola_moto_x_(2nd_gen)-6649.php
Android 6.0

I installed the app using the PlayStore.
When I try to open the app I get a pop up with the error message "Unfotunately, Mifare Classic Tool has stopped working"

**Comment by ikarus23** [comment]
Oh, ok, that is really strange. Have you send the crash report? If so, I can check the stack trace on the Google Play Developer Console.

**Comment by dellagustin** [comment]
I just send a crash report, the title was something like crash at start up

**Comment by ikarus23** [comment]
Thanks, I will have a look into it. But it might take some time. I will be on vacation ;).

**Comment by ikarus23** [comment]
Unfortunately I can not find any crash report of an Moto X 2gen with Android 6.0. But more confusing is, that you was able to install it using Google Play. MCT is blacklisted for the Moto X 2gen because it does not support Mifare Classic (see: https://github.com/ikarus23/MifareClassicTool/issues/1). Are you sure you have a Moto X 2gen?

**Comment by ikarus23** [comment]
Any news on this?

**Comment by dellagustin** [comment]
Sorry, I lost track of this issue.
I sent a new report.
Here is the about section of my telephone:
![image](https://user-images.githubusercontent.com/260113/32276268-b3efb414-bf0e-11e7-882e-a63c20b0ffed.png)

**Comment by ikarus23** [comment]
I'm still not sure what might cause this. But you can try [this testing version](http://tests.icaria.de/MifareClassicTool-2.1.0-testing8.apk) and see if anything changes. Please not that this testing version is not finished yet and might behave "strange". ;)

**Comment by ikarus23** [comment]
Any news on this? Have you tried out the testing version? Or maybe [this other testing version](http://tests.icaria.de/MifareClassicTool-2.1.0-testing10.apk)?

**Comment by ikarus23** [comment]
Lack of feedback. Closed.
Feel free to reopen this after testing the latest version from the Play Store.
