### ISSUE TITLE
More supported models

### ISSUE THREAD

**Issue by tiredboffin** [ikarus23/MifareClassicTool#141]
UPD INCOMPATIBLE_DEVICES.md: MCT works fine on Google Pixel and on Sony Z5 Compact E5823

**Comment by jekkos** [comment]
+1 for google pixel

**Comment by ikarus23** [comment]
That is good news. There are still issues on the Nexus 5X... to bad Google does not really care for the soon outdated phone...

I will update the list.

**Comment by jekkos** [comment]
Pixel uses pn511 apparently. Too bad none of these chips has a full manual available like the pn532... The only chip that we know how to disable parity check on the protocol

**Comment by tiredboffin** [comment]
Isn't it ManualRCVReg (address 1D) Parity Disable Bit 4?

**Comment by jekkos** [comment]
So you know how to configure chip to disable parity checks? Might be useful to get mfoc working.. and program Chinese uid cards

**Comment by ikarus23** [comment]
You probably still need a custom kernel module to make it work...

**Comment by jekkos** [comment]
Hm i thought that the nfc kernel driver was more of a passthrough i2c sink and that most logic is written in userspace? Eg libnfc can do this without installing a custom kernel so not sure if the archirecture for these android NXP chips is that different than from pn532

**Comment by jekkos** [comment]
In fact one would need a libnfc port.. this one has some modular drivers for some nxp chips so might be a matter of adding one for android then

**Comment by ikarus23** [comment]
Devices added to the list of compatible devices. Closed.
