### ISSUE TITLE
Can't write to "protocol command" version mifare zero "magic" cards

### ISSUE THREAD

**Issue by amalg** [ikarus23/MifareClassicTool#142]
The MCT on my Moto X 1st gen works great to read cards but when I try to write it errors. I'm wondering if MCT can support the type of sector 0 writable cards which require a special protocol command to unlock the "backdoor"? 

Here is a run-down of the protocol interaction; http://amal.net/caps/2017-08-16_11-57-40.png

**Comment by ikarus23** [comment]
Hi @amalg, sorry but it is not possible to support these kind of tags. Android does not allow to send custom commands without the CRC. It always append it meaning the command is no longer appear to be valid for the card.
