### ISSUE TITLE
Nothing to correct

### ISSUE THREAD

**Issue by Piket564** [ikarus23/MifareClassicTool#145]
The App also work on LG G6 H870!

_Sent from my Lge LG-H870 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ikarus23** [comment]
Hi, thanks for reporting. I will add it to the list of supported devices.

**Comment by ikarus23** [comment]
Added in 626498a6dffcaa95091e28ea309b250754811ba5. Closed.
