### ISSUE TITLE
Samsung not working with update? [S7 Edge]

### ISSUE THREAD

**Issue by 1213141** [ikarus23/MifareClassicTool#147]
I was wondering if my device could work with this app since it says that my device isn't compatible with the update. I have a Samsung Galaxy S7 Edge, if that helps?

**Comment by ikarus23** [comment]
Any news on this? What exact version of an S7 Edge do you have?

**Comment by ikarus23** [comment]
Any news? Maybe with [this testing version](http://tests.icaria.de/MifareClassicTool-2.1.0-testing11.apk)?

**Comment by ikarus23** [comment]
Lack of feedback. Closed.
