### ISSUE TITLE
Mifare, Write to specific sector and block, nfc-mfclassic, mfcuk, mfoc

### ISSUE THREAD

**Issue by babaga** [ikarus23/MifareClassicTool#151]
Hi!

I'm cooking a little with MiFare cards, I have been able to retreive the A and B keys with MCFUK, and with MFOC I've created a dump with all the sectors containing the data.

I have been able to figure out which sector and block that contains the valueblock and I am able to change it with the android app Mifare Classic Tool, however I cant find out how to do it within linux or other software, when I'm using NFC-MFClassic it wants to overwrite the whole card, which would be fine but I'm having trouble with it saying the UID does not match from the dump and the actual card.

Any ides? thanks for helping!

**Comment by ikarus23** [comment]
Well, you don't have to write the full card if you don't want to. You can use the value block decoder/encoder tool of MCT and write the encoded value using MCT's write block function.

Also, I don't know any windows/linux tool to encode/decode value blocks. But it is not that hard. Just have a look at section 8.6.2.1 of the [Mifare Classic datasheet](http://www.nxp.com/documents/data_sheet/MF1S50YYX.pdf).
