### ISSUE TITLE
Suddenly not working...

### ISSUE THREAD

**Issue by gijoe2cool** [ikarus23/MifareClassicTool#157]
Hello, I have been using this for the past few days now, and suddenly it's saying my device is incompatible. Why would that happen?

**Comment by ikarus23** [comment]
Hmmm, strange. What device are you using? Does it work with [this testing version of MCT](http://tests.icaria.de/MifareClassicTool-2.1.0-testing11.apk)?

**Comment by gijoe2cool** [comment]
Sorry, I forgot I posted here, but I eventually fixed it by restarting my phone, but it's done it once more since then. There doesn't seem to be a set situation either where it happens.

**Comment by ikarus23** [comment]
Ok, thanks for the feedback. I'm closing this issue for now, but if you find out what is causing this issue, please tell me. Maybe we can fix it.

**Comment by gijoe2cool** [comment]
I will let you know the more I play with it.
