### ISSUE TITLE
not work after update [Xperia xz]

### ISSUE THREAD

**Issue by hydra228** [ikarus23/MifareClassicTool#170]
after update do not work with xperia xz android 8.0! 
shows uid but constantly loses connection

**Comment by ikarus23** [comment]
What has been updated? The app or the phone?

**Comment by hydra228** [comment]
app, and phone)))
check it plz

**Comment by ikarus23** [comment]
Could be an issue with the Android ROM. Have you tried the "retry authentication" or "auto reconnect" option of MCT?

**Comment by hydra228** [comment]
no, I'll try it in the next time, write off the result

**Comment by hydra228** [comment]
I set the recommended settings, the problem is not solved

**Comment by ikarus23** [comment]
Closed. Working after setting "retry authentication" and/or "auto reconnect"
