### ISSUE TITLE
How collect Nt on android ?

### ISSUE THREAD

**Issue by maxben14** [ikarus23/MifareClassicTool#171]
Hi, @ikarus23 .
I want collect Nt on android.
Do you know how collect Nt on android ? I want do crypto1-bs tools on android.

**Comment by ikarus23** [comment]
Hi @maxben14. No, I don't know how to do that. But I'm pretty sure it is not possible. At least with the default Android NFC library. As far as I know a custom ROM/Driver/KernelModule is needed.

**Comment by ikarus23** [comment]
I can't quite follow you. What is done at hardware level? Cracking a Mifare Classic tag should be possible at software level. mfoc/mfcuk make it work with a simple USB RFID reader.

**Comment by maxben14** [comment]
I think, that at hardware level nxp chip do nt,nr,ar,at numbers.

**Comment by ikarus23** [comment]
Question answered. Closed.
