### ISSUE TITLE
How to read NTag in This example?

### ISSUE THREAD

**Issue by Jiks19** [ikarus23/MifareClassicTool#173]
Hello,

I tried NFC ntag type using this example.
But can't read it.

Please can you give me any suggestion/help?

Thanks.

**Comment by ikarus23** [comment]
Well, this app is named **MIFARE Classic** Tool. As you can read in the README:
>This tool provides several features to interact with (**and only with**) MIFARE Classic RFID-Tags.

In other words: This app can not read NTags. It's only for MIFARE Classic.

**Comment by Jiks19** [comment]
Thanks for replay.

I have ACR122U external USB device.
I tried read Ntag with external USB device.

ACR122U device mifare cards takes more time to read.
So we need to read ultralight cards.

please give me suggestions / help.

**Comment by ikarus23** [comment]
Sorry, I do not understand your question. What are you trying to do? What's with the read time?
