### ISSUE TITLE
Sector 0 - Corruption

### ISSUE THREAD

**Issue by fabltd** [ikarus23/MifareClassicTool#185]
After editing sector 0 and writing the dump.

Card now reports: No Keys Found (or dead sector)

Is this reversable?

**Comment by rawisha** [comment]
I have an ACR122U and there is a tool that follows, does the job. Just use a dump from a working card and replace it.

**Comment by ikarus23** [comment]
Yes, try a reader like the ACR122U. Also, what exact 4 blocks did you write into the first sector?

**Comment by uchihamadara23** [comment]
I have used the app to read my card but when it finish only the sector 0 is visible... it have 5 sectores (0 to 4) but the sector 1, 2, 3 and 4 says "No keys found (or dead sector)"... what that means?

**Comment by ikarus23** [comment]
@uchihamadara23, well it means exactly that. None of the keys in the key file you provieded contained a valid key. You can't just read a Mifare Classic tag. You need the keys (passwords). Have a look at the [Getting Started](https://github.com/ikarus23/MifareClassicTool#getting-started) section of the readme file.

And there is also the "dead sector". If you wrote invalid access conditions to a tag, the sector will permanently break and will no longer be usable.

**Comment by ikarus23** [comment]
As this is most likely not related to MCT, I will close it. Feel free to document your success/error in trying to reverse the changes you've done.
