### ISSUE TITLE
No keys found (or dead sector) android 8.0 + MI6

### ISSUE THREAD

**Issue by Aqho** [ikarus23/MifareClassicTool#190]
Hello, previously i have a one plus one, he just finish he's life :'( RIP him,
So i'm now on a Xiaomi MI6 (global 6Go version) and MCT seems to have some trouble with it.
I'm actually on Miui 10 Global android 8.0.0 and i have this error(same trouble on miui 9):
using a mifare classic 1K and only on sector 14 - 15
No keys found (or dead sector) 

the keys are currently 000000000000 and FFFFFFFFFFFF on these sectors and mct can't read it, other app like MFClassic arrived with the same keys...
![screenshot_2018-07-10-10-41-15-961_de syss mifareclassictool 1](https://user-images.githubusercontent.com/12032349/42498920-cae8a024-842d-11e8-8f45-6d54848f0599.png)
![screenshot_2018-07-10-10-37-26-295_de syss mifareclassictool 1](https://user-images.githubusercontent.com/12032349/42499013-002779ea-842e-11e8-9ff9-175de160a2e0.png)
![screenshot_2018-07-10-10-39-55-820_com touf mfclassic 1](https://user-images.githubusercontent.com/12032349/42498963-e0722730-842d-11e8-9cdf-01a36ebed251.png)

thank's for reading me :) sorry for my poor english
Nice work on mct btw, awesome tool!

**Comment by ikarus23** [comment]
Any news on this? Could you try apps like "NFC TagInfo"?

**Comment by ikarus23** [comment]
Lack of feedback. Closed.
Feel free to give feedback/reopen the issue once you tried other apps like "NFC TagInfo"!
