### ISSUE TITLE
Unable to clone

### ISSUE THREAD

**Issue by RasmusKallas** [ikarus23/MifareClassicTool#191]
Hey, I'm unable to clone my Tallinn's Transport card again, I got it working finnally on 1 card, but now with same specced keyfobs I am unable to clone again, when comparing original and cloned key, the last block on each sector (so the last line) on cloned is FFFFFFFFFFFFFF078069FFFFFFFFFFFF (so it's the default) and on original sector 0 is A0A1A2A3A4A50F078FC1------------ and up to the 6th D3F7D3F7D3F70F078F41------------ (others are all zeroes).
I understand, that dashes mean unreadable/ununderstandable to the app, but I had the same results when I cloned the cloned card  and got it working (think so at least). Some Chinese things arrive 2-3 months from ordering. i needed to reinstall the app, since I factory erased my phone. The original card I read is the same, but it may not be the same dump generated with the cloned card. Also I lost the cloned card and my OnePlus 5t has had OTA updates.
Thanks for an awesome app anyways!

**Comment by ikarus23** [comment]
Well, MCT can not write a block with incomplete information. The "---" means the data is unknown. You can write Mifare Classic tags only block-wise. This means: You can't write a complete clone if the dump contains unknown ("----") data.

**Comment by RasmusKallas** [comment]
How can it be unknown? :( and even if you can't recognize it, can't you just dump it (like a powershell programmer copies some node.js so it would just work)

"just work" it never works

**Comment by ikarus23** [comment]
> How can it be unknown?

Well, you don't know key B. The --- at `A0A1A2A3A4A50F078FC1------------` is where key B is saved. So no, I can't just read it and without knowing it I can't copy or dump it. You need all keys to read a full Mifare Classic tag.
