### ISSUE TITLE
Making a Clone card successful (0~15dump same) but  Elevator is not responding

### ISSUE THREAD

**Issue by a9029461** [ikarus23/MifareClassicTool#196]
hello 

sorry for my english...

i used mifare classic tool 

so successful to make clone card. 

it same uid and same Sector 0~15.

card type is mifare classic 1k card. so i use cuid and scuid 

it works for door! but not responding elevator.. 

touch the card to the elevator leader them my floor light on.

but my clone cuid and scuid key is not responding for elevator

someone know how to fix the problem?

**Comment by ikarus23** [comment]
Are the tags 100% identical? You can use the "Comare Tool" of MCT.

**Comment by ikarus23** [comment]
Any news on this?

**Comment by ikarus23** [comment]
Lack of feedback. Closed.
