### ISSUE TITLE
Please add a list of devices that works with MCT

### ISSUE THREAD

**Issue by Moelf** [ikarus23/MifareClassicTool#20]
Known a list of devices that does not work. How about add a list that name a few devices that work perfectly with MCT?

**Comment by kofdasad** [comment]
Which one can be the cheapest with MifareClassicTool/Mifare Classic support?
My S4 is not good at that
:v

**Comment by ikarus23** [comment]
Sorry, I really don' t know. Some guy at the proxmark3 said
> Philips Xenium I908 works like a charm! Its the most cheapest up to date platform for the app available nowadays

But if you don't care on the *up to date* there should be cheaper ones. An old Nexus S or an Samsung Galaxy S3 should do the trick es well.

Also, have a look at the bottom of [this list](https://github.com/ikarus23/MifareClassicTool/blob/master/INCOMPATIBLE_DEVICES.md). Maybe one of them is really cheap

**Comment by lambia** [comment]
I'd like to report these one:

Working:
- LG G4 (H815)
- LG G3
- ZTE Axon 7
- Xperia Z3
- Huawei P8 Lite 2017

Not working:
- LG G2
- Samsung S8
- Samsung S5 mini

**Comment by ikarus23** [comment]
@lambia Thanks for reporting. I will check which one of there is already on [COMPATIBLE_DEVICES.md](https://github.com/ikarus23/MifareClassicTool/blob/master/COMPATIBLE_DEVICES.md) or [INCOMPATIBLE_DEVICES.md](https://github.com/ikarus23/MifareClassicTool/blob/master/INCOMPATIBLE_DEVICES.md) and which not.

**Comment by rawisha** [comment]
You can add mate 10 pro to the compatible list also.

**Comment by pmorange** [comment]
And galaxy S8 to the incompatible 😑

**Comment by ikarus23** [comment]
Thanks, I updated the lists.
Athough with the "retry authentication" feature the Huawei Mate 10 Pro works, I did not add it to the list because of https://github.com/ikarus23/MifareClassicTool/issues/158. Compatible should be 100% compatible without strange behavior ;)

**Comment by lambia** [comment]
Nokia 8 has compatible NXP chipset and MiFare works like a charm, although some Nokia 8 seems to suffer of "Found new tag" loop. Anyway finding to good spot near the antenna, and holding a card firmly on it will do the magic. A lot of Nokia8 users reported me as "not working", just for this problem. So I hope this post can help out someone.

**Comment by ikarus23** [comment]
Hi @lambia! Thanks for the heads up. I will consider to add the Nokia 8 to the list of compatible devices (and hope the users will be smart enough to figure out the antenna issues).

**Comment by apnof** [comment]
Working: BQ Aquaris X Pro

**Comment by 2thewes** [comment]
The Sony Xperia X Compact (with Android 8.0) is also working.

**Comment by ikarus23** [comment]
> The Sony Xperia X Compact (with Android 8.0) is also working.

Interesting. This device was reported to me as not compatible. Did it started to work since Android 8?

**Comment by 2thewes** [comment]
> Interesting. This device was reported to me as not compatible. Did it started to work since Android 8?

I don't know. I have not tried it before I updated to Android 8.
