### ISSUE TITLE
[Android 9] Black text on dark grey menu

### ISSUE THREAD

**Issue by bennesp** [ikarus23/MifareClassicTool#200]
As title, each menu of the app on Android P (on Oneplus 6) has black text on dark grey background. This unfortunately makes using the app very difficult, especially in daylight situations.

Screenshot:

![photo_2018-09-24_21-01-11](https://user-images.githubusercontent.com/5445545/45973202-0f2e5480-c03e-11e8-9046-46e18d90bd66.jpg)

**Comment by bennesp** [comment]
Maybe a OnePlus related thing so. Just to be clear, the above bug seems to happen even changing the Oneplus6 android theme (Dark/Light/Colors).  If there is something I can do to help in the debugging, please let me know.

**Comment by ikarus23** [comment]
Intersting. How does this testing version of MCT (with Material Theme) work out for you? http://tests.icaria.de/MifareClassicTool-2.2.3-testing4.apk

**Comment by bennesp** [comment]
This version is working perfectly 🤩

**Comment by ikarus23** [comment]
Great! I pushed to the master branch so it will be part of the next release.

**Comment by ikarus23** [comment]
I had to change some small things. Could you please try [this testing version](http://tests.icaria.de/MifareClassicTool-2.2.3-testing5.apk) and see if it is still working properly? Thanks!

**Comment by bennesp** [comment]
Just to let you know, I have just discovered that the problem was appearing
also in Android 6 in a P8 Lite.
But the last apk is working perfectly 👍
Thank you for your time

Il gio 27 set 2018, 20:31 ikarus <notifications@github.com> ha scritto:

**Comment by ikarus23** [comment]
Thank you too. I noticed this bug too on a Samsung S9. Really strange. Well I guess it's working now. ;)
