### ISSUE TITLE
no valid key found in chosen key file

### ISSUE THREAD

**Issue by tibi14** [ikarus23/MifareClassicTool#201]
no valid key found in chosen key file
what does it mean ?
I use a samsung s9+

**Comment by ikarus23** [comment]
Well it means exactly that. None of the keys in the key file you provided contained a valid key. You can't just read a Mifare Classic tag. You need the keys (passwords). Have a look at https://github.com/ikarus23/MifareClassicTool#general-information and https://github.com/ikarus23/MifareClassicTool#getting-started

From the Readme:
>This app is designed for users who have at least basic familiarity with the MIFARE Classic technology.

Please, at least try. ;)
