### ISSUE TITLE
Can't read the tag (Have the keys)

### ISSUE THREAD

**Issue by Elsin10** [ikarus23/MifareClassicTool#205]
I tried to read the card after getting the keys with proxmark3 but it shows this
![nfc-bilhet](https://user-images.githubusercontent.com/39327656/46898771-7e8bad00-ce62-11e8-8d08-ccacea835133.png)

This are the keys, i think, that i got from the card. I've added them to MCT
![bilhun-keys](https://user-images.githubusercontent.com/39327656/46898778-98c58b00-ce62-11e8-9f07-2f9ae9b6ab8d.png)

I added this two: de1fcbec764b and 400bc9be8976
So what is the problem ?

[edit]
I've added all the keys in the KEYS file, now im able to read the rest.

**Comment by ikarus23** [comment]
Now that you able to read the rest, does the first sector still have the `---` as key b?

**Comment by ikarus23** [comment]
Any news?

**Comment by ikarus23** [comment]
Lack of feedback. Closed.
