### ISSUE TITLE
MIUI could read a card but LineageOS didn't

### ISSUE THREAD

**Issue by wbsdty331** [ikarus23/MifareClassicTool#209]
Hi ikarus,
I am using Xiaomi 5(gemini),When I use MIUI 10, use MCT to read or write a JCOP card have no problem, just sometimes MCT Notice it's not Mifare Classic Tags, But sometimes it works.

But I flashed LineageOS 15.1, no matter what i do, MCT said "Not Mifare Classic Tags",I don't know why.

Thanks.

**Comment by ikarus23** [comment]
Hi!
Hmm... a JCOP card in Mifare Classic emulation mode can have different SAK values, for example. This might trick Android (or MCT?!) into thinking it is not a Mifare Classic tag.

However, I have no clue why it worked with MIUI sometimes. Maybe this operating system handles this tag different (e. g. because of its SAK value).

**Comment by wbsdty331** [comment]
I don't know why :(
Should I provide some log?

**Comment by wbsdty331** [comment]
Or How to compare these ROM SAK Value?

**Comment by ikarus23** [comment]
Sorry for not answering earlier. I somehow overlooked your message.
Unfortunately, I don't know what to do. Have you checked other apps? Are they able of reading/writing Mifare Classic?

**Comment by wbsdty331** [comment]
I tried use TWRP to switch system between MIUI and Lineage OS, use a same card.
When I done, I will upload some information.
 
BTW, Where is log?

**Comment by wbsdty331** [comment]
same as NFC Tools
![screenshot_2018-12-07-08-51-17-660_com wakdev wdnfc](https://user-images.githubusercontent.com/4280572/49620772-57360400-f9fd-11e8-8e55-0d646fab85cb.png)
![screenshot_2018-12-07-08-51-25-348_com wakdev wdnfc](https://user-images.githubusercontent.com/4280572/49620773-57ce9a80-f9fd-11e8-9b26-b4f93561e8e4.png)

Sometimes 0x20 but sometimes 0x28.

**Comment by ikarus23** [comment]
Well, this is interesting. This proves something is wrong with the OS (drivers) or the tag itself (and not the MCT app). Do you have access to another Android phone? You could try another device to find out if the tag is faulty or the OS.

**Comment by wbsdty331** [comment]
Tested my roommate's Huawei Honor 10
Like MIUI but not test on Lineage

**Comment by ikarus23** [comment]
It has the same strange behavior with a different OS? I'm starting to believe there is something wrong with the tag.

**Comment by wbsdty331** [comment]
yes.

**Comment by ikarus23** [comment]
I will close this issue since it seems it is not related to MCT but the tag or the OS. Feel free to leave any feedback if you find out what exactly is causing this issue.
