### ISSUE TITLE
Allow option to disable the app automatically starting when an nfc tag approaches

### ISSUE THREAD

**Issue by devedse** [ikarus23/MifareClassicTool#212]
I'm currently using an android cover with a slot for an nfc card. However whenever I open this cover, the nfc card touches the backside of my phone and the Mifare Classic App opens.

Is this something we can make configurable?

![20181026_112335](https://user-images.githubusercontent.com/2350015/47558133-b25edc00-d912-11e8-8eb3-81abd8d76d42.jpg)

**Comment by ikarus23** [comment]
Hi, this feature was requested before. Have a look at https://github.com/ikarus23/MifareClassicTool/issues/97. Until now however, I don't know of a way to make this happen.

**Comment by ikarus23** [comment]
Closed as duplicate of https://github.com/ikarus23/MifareClassicTool/issues/97. Let's continue the discussion over there, if there are any news.

**Comment by ikarus23** [comment]
It works since d6eb7d150cc186509718c18abcfe1ba9ddc8f6b2 thanks to @aerizzo. The feature will be included in the next release.
