### ISSUE TITLE
Treat backward compatible desfire cards as mifare classic

### ISSUE THREAD

**Issue by HrBDev** [ikarus23/MifareClassicTool#216]
According to Mifare DESFire documentation, there is a backward compatibility mode with Mifare classic cards, I believe I have one of these cards, Is it possible to treat these cards as Mifare classic in the app?

**Comment by ikarus23** [comment]
I'm not sure about Mifare DESFire, but there is Mifare Plus. Mifare Plus tags are compatible to Mifare Classic tags as long as they are in SL0 or SL1 mode. Therefore, MCT should be able to read/write them as long as there are in the right SL.
