### ISSUE TITLE
import/exprot of bin/eml/json (proxmark3/mfoc file format compatibility)

### ISSUE THREAD

**Issue by ikarus23** [ikarus23/MifareClassicTool#217]
Tools like the Proxmark3 can handle files like `.bin`, `.eml` and `.json`. mfoc always need `.bin` files. MCT has his own file format (`.mct`). Therefore it would be great if MCT can import and export from/to these file formats.

For now there are scripts in the tools folder which can do this. At least for `.bin`, `.eml` and `.mct`.

**Comment by iceman1001** [comment]
Might just add that we are talking about dump files :)  
Getting support for MCT or a converter into proxmark3 / chameleon mini gui  would also be beneficial

**Comment by iceman1001** [comment]
Now the chameleon mini gui has support for MCT format.   Where  can I find a MCT dump to test?

**Comment by ikarus23** [comment]
Great!
https://github.com/ikarus23/MifareClassicTool/blob/master/tools/example-files/example-dump-file.txt

**Comment by iceman1001** [comment]
Works like a charm with that test file.

**Comment by ikarus23** [comment]
Started to work on it at [import-export](https://github.com/ikarus23/MifareClassicTool/tree/import-export) branch. Not sure how it will take. Depends on my free time ;)

**Comment by iceman1001** [comment]
Things takes time,  that is how it works.

**Comment by ikarus23** [comment]
Added with 9502877b45bbfaed38afdb123256eb10d934d884.
