### ISSUE TITLE
"Write the manufacturer block of special MIFARE Classic tags" missing

### ISSUE THREAD

**Issue by thestamp** [ikarus23/MifareClassicTool#219]
There isn't an option to enable the "Write the manufacturer block of special MIFARE Classic tags" setting. Is this only available in the APK?

**Comment by ikarus23** [comment]
No, it is present in every version. Maybe you just did not saw it. You have to check the "Show options" box in the "Write Dump" section.

If you just want to write block 0 (not a whole dump) then use the "Write Block" section. Select sector 0 block 0. There is no need for some special option.

**Comment by ikarus23** [comment]
I hope you found it. ;)
Closed.

**Comment by thestamp** [comment]
Yup! Works perfectly! Thank you!
