### ISSUE TITLE
NFC repeatedly read

### ISSUE THREAD

**Issue by g5user** [ikarus23/MifareClassicTool#223]
Hi,
I have the issue with on-screen notification "NFC repeatedly read ..... to save battery etc."
I have LG G5 and it was working in March. Now when I try to read tag I have this info and connection is lost. I think it is connected to the latest system update but I can't be sure.
Now I have Android 8.0.0 version.
A similar issue was reported some time ago but it's closed so I opened new and I hope there is a good solution for this
Any hints would be appreciated?

**Comment by ikarus23** [comment]
I reopend https://github.com/ikarus23/MifareClassicTool/issues/70. But so far I have no hint upon fixing this.
