### ISSUE TITLE
I can not read card by acr122u without NFC. 

### ISSUE THREAD

**Issue by kgamecarter** [ikarus23/MifareClassicTool#225]
I can use External NFC detect card. And my phone without NFC. 
But read and write button still disabled. 
![screenshot_20190109-054043](https://user-images.githubusercontent.com/3646532/50860808-d5f1d880-13d1-11e9-80da-003c25b1bd41.jpg)

**Comment by ikarus23** [comment]
This really looks like a bug in MCT. But be warned: People report that External NFC is not working correctly (https://github.com/ikarus23/MifareClassicTool/issues/198 or https://github.com/ikarus23/MifareClassicTool/issues/123#issuecomment-388307001). I will look into it, but it might take some time.

**Comment by ikarus23** [comment]
Is the External NFC service running correctly? I can't see the symbol at the top of your screenshot. And was there any error message? MCT tries to find out if External NFC is installed and running. If so, the buttons should be operable. I have no device without NFC right here, but I will borrow me one to check if I get the same behavior.

**Comment by ikarus23** [comment]
Ok, I found the bug. MCT uses [getRunningServices(int)](https://developer.android.com/reference/android/app/ActivityManager.html#getRunningServices(int)) to find out if External NFC is running. `getRunningServices(int)` however is deprecated and no longer works. I will try to find a fix.

**Comment by ikarus23** [comment]
I tested it with the device of a friend and it seem to work. Have you been able to test it?

**Comment by kgamecarter** [comment]
Ok, Is's work now.
Thanks update.
![img_20190201_011802](https://user-images.githubusercontent.com/3646532/52072112-536acc00-25bf-11e9-9786-9368a2835053.jpg)

**Comment by ikarus23** [comment]
Great! The code is in the master branch and will be part of the next release.
