### ISSUE TITLE
ISO/IEC 14443, Type A is not recognized [ZTE V9 Vita (V0920)]

### ISSUE THREAD

**Issue by jn0** [ikarus23/MifareClassicTool#227]
It's display a balloon of "unrecognized tag" or so, but in Tag Info section one may read:

![image](https://user-images.githubusercontent.com/407437/51901531-f279a300-23c8-11e9-8ae2-b38256b8fa4c.png)

**Comment by ikarus23** [comment]
It looks like a normal Mifare Classic tag. Has nothing to do with raw ISO 14443 commands. What are the exact issues you are having? What happens if you try to read it?

**Comment by ikarus23** [comment]
Any news?

**Comment by ikarus23** [comment]
Closed. Lack of feedback.
