### ISSUE TITLE
Does the Samsung Galaxy Note 9 support Mifare Classic?

### ISSUE THREAD

**Issue by wiesel25** [ikarus23/MifareClassicTool#234]
Hello,
i would like to buy a Samsung Galaxy Note 9.
Can someone tell me on this phone is supported by MifareClassicTool.

Thanks

W.P

**Comment by gcammisa** [comment]
I successfully tested reading and writing to a mifare classic 1k with a Galaxy Note 9 (EMEA market, the variant with Exynos 9810 cpu)

**Comment by ikarus23** [comment]
@gcammisa Thanks for the feedback. Closed.
