### ISSUE TITLE
Write block 0

### ISSUE THREAD

**Issue by silva96** [ikarus23/MifareClassicTool#24]
I changed the block 0 in order to change the card uid, It look's it has changed but when I read the card It says "Tag found: ..." and shows always the same id

**Comment by AnArchoz** [comment]
So I have had no issue with MCT (apart from the galaxy S5 lollipop-problem you swiftly fixed), but now it seems it won't correctly write manufacturer block from dump, and has 9 differences in the block. I can not say for certain that the tag is not damaged - it's been in other hands for a few days -, but it's the only block that differentiates from the original dump.

**Comment by AnArchoz** [comment]
I can assure you the specific tag has sufficient authority to write manifacturer block as I have done this since november. It's only now I am experiencing this problem.

**Comment by AnArchoz** [comment]
Actually, it looks like I have been given the wrong tag. Please disregard everything above ;_;

**Comment by ikarus23** [comment]
Hehe, I'm just glad everything worked out. ;)

**Comment by ikarus23** [comment]
Closed. @silva96 did not answer.
