### ISSUE TITLE
Incomplete update from Play Store

### ISSUE THREAD

**Issue by david-wm-sanders** [ikarus23/MifareClassicTool#244]
Updating the app to v2.2.6 via the Play Store did not update the included keyfiles to the latest versions that are included in this repository.

**Comment by ikarus23** [comment]
Yeah, sorry, the update is pretty dumb. You have to remove the old key file to get the new one.

**Comment by david-wm-sanders** [comment]
Ah, fair enough. That actually makes more sense. Thank you :)
