### ISSUE TITLE
Wrong error messages on MIFARE Classic support when using an external reader.

### ISSUE THREAD

**Issue by joescorr** [ikarus23/MifareClassicTool#247]
My main issue here is the popup saying that my device isn't supported, even with an ACR122 plugged in. Any way I can disable that warning?

Thanks

**Comment by ikarus23** [comment]
What device are you using? Have you installed External NFC?

**Comment by ikarus23** [comment]
Any news?

**Comment by joescorr** [comment]
Apologies for the delay,
I can get MCT to work with my USB reader, but the popup stating that my phone isn't supported (even with the USB plugged in and working) makes using MCT's UI a nightmare

**Comment by ikarus23** [comment]
What exact error message is shown when?

**Comment by Lexus89** [comment]
Any update about this? I am currently looking for a SCL3711 to connect to my Nexus 5 phone and hope MTC will work with that. From what i understand this should be possible right?

**Comment by joescorr** [comment]
If your device isn't supported, it will show error messages saying that it
won't work, but will work just fine after you close them.
The error messages are more annoying than an actual issue

**Comment by ikarus23** [comment]
Oh, ok. So you got External NFC installed and it works but when you start MCT it detects your device is not supporting Mifare Classic and show you a warning that you can not use it? Because MCT should check if External NFC is installed. What Android version are you using and what is the exact error message?

**Comment by ikarus23** [comment]
Any news?

**Comment by ikarus23** [comment]
I've just had a deeper look into the source code and I think I see what might cause this issue for some users. I will try to fix it and report back with a testing version for you guys to check out.

**Comment by ikarus23** [comment]
I've build a testing version of MCT which should make this better. Please try it out! http://tests.icaria.de/MifareClassicTool-2.3.1-testing4.apk

**Comment by ikarus23** [comment]
The fix is released with version 3.0.0. If it does not work, feel free to reopen this issue.
