### ISSUE TITLE
New phones that support NFC MIFare classic

### ISSUE THREAD

**Issue by maria1andersson** [ikarus23/MifareClassicTool#253]
Hello 
Thank you for this app 
PLZ what is New phones that support NFC MIFare classic ?

**Comment by ikarus23** [comment]
Not sure about "new" phones. But you can have a look at https://github.com/ikarus23/MifareClassicTool/blob/master/COMPATIBLE_DEVICES.md

**Comment by cosmocain** [comment]
Hello @ikarus23 , along with greeting and wishing that you continue contributing with the mct app, I have the doubt regarding a nokia 4.2 device will the app work with an android 9 for example?
What do you recommend to see the compatibility with the apk?
regards

**Comment by ikarus23** [comment]
@cosmocain There is only one good way to check the compatibility. Get the device and an Mifare Classic tag. Then try to read and write to the tag. If it works everything should be fine.

Unfortunately there is no good way to tell if a device is supported without trying. There are only some list available, but they might be wrong:
* https://github.com/ikarus23/MifareClassicTool/blob/master/COMPATIBLE_DEVICES.md
* https://github.com/ikarus23/MifareClassicTool/blob/master/INCOMPATIBLE_DEVICES.md
* https://www.shopnfc.com/en/content/7-nfc-compatibility

**Comment by cosmocain** [comment]
Hi @ikarus23 
Yesterday I did a direct test on a Nokia 6 device which I loaded the mct app and opened without any problem, also recognized the mifare label.
I give it to you as data for you to include in your list.
regards

**Comment by alierta** [comment]
Hello I have a Huawei Mate 20 and mct works perfectly. Can read and write mifare classic without any issue with android 9. Tested by me. It can be added to compatible devices.

**Comment by alierta** [comment]
And Oneplus 6T works too. I tested it. Thanks @ikarus23 for the app. If you need some screenshot or something I can provide it.

**Comment by ikarus23** [comment]
Thanks! I will update the list of compatible devices.

**Comment by comp500** [comment]
I have a Nokia 6.2 (Android 9), and it works as well. It seems likely that the 4.2 will support Mifare Classic if it has NFC, they probably use the same NFC chip.

**Comment by ikarus23** [comment]
I guess this issue has been there for long enough. Don't forget to check the list of [compatible devices](https://github.com/ikarus23/MifareClassicTool/blob/master/COMPATIBLE_DEVICES.md).
