### ISSUE TITLE
Why i can't write 4k?

### ISSUE THREAD

**Issue by hydra228** [ikarus23/MifareClassicTool#254]
I got DUMP MIfareCLassic 4k with ATQA:0x0042 and SAK: 0X18
MCT app can't wtrite it

**Comment by ikarus23** [comment]
There are a lot of information missing. Do you have the keys? Do the access conditions allow you to write to the blocks?

**Comment by ikarus23** [comment]
Any news?

**Comment by ikarus23** [comment]
Closed. Lack of feedback.

**Comment by hydra228** [comment]
All worker perfectly
Write 4k damp to 1k card, just need chose only 15 block!
Autor respect
