### ISSUE TITLE
Can you allow Galaxy S7 Active?

### ISSUE THREAD

**Issue by padillla** [ikarus23/MifareClassicTool#261]
I have a galaxy S7 active, the other S7 are listed in the compatible devices, but for some reason my s7 shows as incompatible, please modify the Play settings to allow Samsung SM-G891A to use this app. 

Thank you

**Comment by ikarus23** [comment]
Well, have you tested MCT on the S7 Active? Did it start to work since Android 8?

**Comment by padillla** [comment]
I'd like to

**Comment by ikarus23** [comment]
I thought you already did ;) Just install the app from http://publications.icaria.de/mct/releases/.

**Comment by ikarus23** [comment]
And does the S7 Active have Android 8?

**Comment by padillla** [comment]
Yes, it has android 8, I will download it from there.

This app, allows cloning or reprogram of HID cards, right?

thank you

**Comment by ikarus23** [comment]
No. It is for Mifare Classic cards only. That's why it's named "Mifare Classic Tool".

**Comment by ikarus23** [comment]
I guess this done now.
