### ISSUE TITLE
Special Cards

### ISSUE THREAD

**Issue by proddick** [ikarus23/MifareClassicTool#262]
Any suggestions where I can get some of the special writeable cards? I bought some that don't work for sector 0.

**Comment by ikarus23** [comment]
Have a look at https://github.com/ikarus23/MifareClassicTool/issues/221#issuecomment-449133889,

**Comment by proddick** [comment]
I was hoping to get some quicker than 30 to 60 days. Anyone managed to find any in Europe?

**Comment by ikarus23** [comment]
Sure, but they are much more expensive. Check https://lab401.com/collections/rfid-badges for example.
