### ISSUE TITLE
dump editor on the Meizu m16S

### ISSUE THREAD

**Issue by Belllock** [ikarus23/MifareClassicTool#271]
encountered such a bug:
I tried to change the screen scale and font size - it does not help. what can be done so that 32 characters are in one line!?
Thank!
![S90926-14260295](https://user-images.githubusercontent.com/55865266/65739527-0368e880-e0ff-11e9-93c1-b71aa01be098.jpg)

![S90926-14265592](https://user-images.githubusercontent.com/55865266/65739532-05cb4280-e0ff-11e9-886b-bbd878e7a5f2.jpg)

**Comment by ikarus23** [comment]
This is strange. Does [this testing version](http://tests.icaria.de/MifareClassicTool-2.3.1-testing1.apk) work better?

**Comment by ikarus23** [comment]
Or maybe [this testing version](http://tests.icaria.de/MifareClassicTool-2.3.1-testing2.apk)? On the first the text will most likely not be centered.

**Comment by Belllock** [comment]
No. Nothing changed. The second version only centers the text

![S90928-20254062](https://user-images.githubusercontent.com/55865266/65818829-e03d5680-e22e-11e9-84e5-eeebbcfce7e3.jpg)

**Comment by ikarus23** [comment]
Hmm, this was somehow expected. But it should work in the first place. It might be a bug in the Android ROM of your phone. The text boxes for each sector have the layout attribute `WRAP_CONTENT` so the should be as wide as the text within it. Never heard of anybody with the same issue... Do you have the possibility to install another ROM to your phone? Just to check...

**Comment by ikarus23** [comment]
Although I think your ROM is broken, I tried another workaround. Please test it: http://tests.icaria.de/MifareClassicTool-2.3.1-testing3.apk

**Comment by Belllock** [comment]
nothing changed. :( I'll try to ask other owners Meise 16s about this problem). Thanks for the help!

![S91004-09235951](https://user-images.githubusercontent.com/55865266/66181250-8357fb00-e689-11e9-84c2-76d192872747.png)

**Comment by ikarus23** [comment]
In that case I don't think there is much I can do. It seams something is wrong with Android on the device. It just won't wrap the content of text input fields correctly.

**Comment by ikarus23** [comment]
I'm closing this because there is nothing I can do. Sorry. Feel free to provide feedback if you manged to fix it. Maybe an future Android update will make this right.
