### ISSUE TITLE
Can't share dump files

### ISSUE THREAD

**Issue by selxoz** [ikarus23/MifareClassicTool#274]
This issue occurs on Huawei P30 pro. It just says error: sharing file failed

**Comment by ikarus23** [comment]
Interesting. What Android version are you using?

**Comment by ikarus23** [comment]
Is it Android 10?

**Comment by selxoz** [comment]
> Is it Android 10?

It's Android 9

**Comment by selxoz** [comment]
It's Android 9

**Comment by selxoz** [comment]
I think I found the culprit, it's in the preferences. If "Save dump and key files to the internal storage" is unchecked then it's possible to share the dump files. But only the ones which have been saved with this option unchecked.

**Comment by ikarus23** [comment]
Oh, interesting catch! This makes sense. I guess I made some mistake there. I will look into it.

**Comment by ikarus23** [comment]
Fixed with 35af53ba2548f3f67f4988ef29164a8b33a6cbdf. Thanks for reporting.
