### ISSUE TITLE
Error: BCC of block 0 is not valid

### ISSUE THREAD

**Issue by Bulte01** [ikarus23/MifareClassicTool#277]
Hello Everyone,

When I try to write to my card I get the error "Error:BCC of block 0 is not valid".
I have this card to write to [https://www.ebay.nl/itm/5PCS-UID-Changeable-Keyfob-Compatible-with-MCT-Block-0-Direct-Writable-by-Phone/272654995341?ssPageName=STRK%3AMEBIDX%3AIT&_trksid=p2060353.m2749.l2649](url)

Kind regards,

Bas

**Comment by ikarus23** [comment]
The tags look good. But data you are trying to write is not correct. Like the error says, the BCC is not correct. For MIFARE Classic tags with a 4 byte UID, the BCC must be the 5th byte of the very first block (manufacturers block). This app has BCC calculator tool. More information about calculating the BCC and how it is used during the anti-collision phase can be found in NXP's [AN10927](https://www.nxp.com/docs/en/application-note/AN10927.pdf).

**Comment by ikarus23** [comment]
Any news on this?

**Comment by Bulte01** [comment]
> Any news on this?

Nope cannot find the solution

**Comment by ikarus23** [comment]
I did wrote what is causing this error message, so you should be able to fix your data.

**Comment by Bulte01** [comment]
> I did wrote what is causing this error message, so you should be able to fix your data.

I have no idea how to fix it and I have not many experience with NFC chips

**Comment by ikarus23** [comment]
Like I said, you have to make sure the data you are writing is correct. In your case, block 0 is not correct. If you just want to copy the UID, the easiest way it to use the "Clone UID" tool.

**Comment by ikarus23** [comment]
I will close this for now. You should be able to get everything going. Just take your time and learn more about MIFARE Classic. ;)
