### ISSUE TITLE
Make log or screenshot of 'swiped' cards

### ISSUE THREAD

**Issue by voidnecron** [ikarus23/MifareClassicTool#283]
Hi,

I'd love to see a feature to enable logs or screenshots for all tags that have been 'seen' by MCT.
This way a UID clone can be done later for more than one tag (since only the last one is remembered in the clone tool) without having to write them down manually.

Cheers and great job, really love the app!

**Comment by ikarus23** [comment]
Makes sens and it should not be that hard to implement a log. I will try to make this happen, but it might take some time.

**Comment by ravkr** [comment]
That would be a nice feature!

**Comment by ikarus23** [comment]
Done. It's in the master since 38950f89615c01ef0b090c83b3ec4d8fdc5f52fb.
