### ISSUE TITLE
compatible with WearOS?

### ISSUE THREAD

**Issue by mzichao1977** [ikarus23/MifareClassicTool#285]
Does this tool work on smartwatch? I'm looking for a wearOS app to verify the possibility of NFC tag R/W on Android smartwatches that currently support NFC Payment and not much else. 

Another NFC-related question, why is NFC tag R/W feature not natively supported on Android smartwatches? Most smartphones do.

Thanks in advance.

**Comment by ikarus23** [comment]
Hi,
sorry I have no clue of what smartwatches are capable these days. This app however was not designed for smartwatches. I don't think it will work properly.

I don't know the NFC API of smartwatches. Also, I don't think there is "one" API. There are a lot of different smartwatch operating systems out there. Maybe this is also the reason why there is no proper native R/W. Then again, there is no real native R/W on Android as well. Only R/W according to ISO standards...
