### ISSUE TITLE
New tag found interupt key mapping

### ISSUE THREAD

**Issue by MinaroShikuchi** [ikarus23/MifareClassicTool#286]
During the key map progress, finding a new tag interrupt the progress and reset it.
It happens at any moment during the progress.

Thanks. 

Huawei P10
Android 7.0

**Comment by ikarus23** [comment]
Sounds to me like a bad antenna. Try to reposition your tag or remove the phone cover (if there is any).

**Comment by MinaroShikuchi** [comment]
Ok I will see. To not be interrupted I can choose to map fewer sector each times. Like 4 by 4.
