### ISSUE TITLE
我用mct添加一些已知密钥时，它显示不是十六进制！！

### ISSUE THREAD

**Issue by lcq666** [ikarus23/MifareClassicTool#291]
![Screenshot_2020-03-16-20-34-03-245_de syss MifareClassicTool](https://user-images.githubusercontent.com/59388586/76759089-e72b3780-6782-11ea-93cc-e1441c8a741b.png)

以下是我添加的密钥：
7E3D5A01B5E0
2C6E99455E3A
49950410B212
20FD378DBE45
D168DEE8ADED
FFFFFFFFFFFF
6013E2FA096B

我希望添加已知的密钥能解除这个限制！

**Comment by ikarus23** [comment]
Not sure what you want. I do not speak Chinese. Do you want me to add the keys? What do you know about the keys? Are they unique to a card? Or to an installation? Are they the same on all cards of the same product?

**Comment by lcq666** [comment]
When I used this software to add my known key, it made an error, indicating that the key is invalid, not hexadecimal number, can this limit be removed? I added the following key, and then there was an error!

7E3D5A01B5E0
2C6E99455E3A
49950410B212
20FD378DBE45
D168DEE8ADED
FFFFFFFFFFFF
6013E2FA096B

When I add the key of appeal, it will prompt me the problem of appeal. I hope this restriction can be lifted when I add the key. Thank you!

**Comment by ikarus23** [comment]
Interesting, the look OK to me. Are you sure the lines are correct? No whitespaces at the end? Did you paste them from a non-ASCII source? A key should be 12 hexadecimal characters.

**Comment by ikarus23** [comment]
I copied the keys to my phone and everything worked.

**Comment by lcq666** [comment]
Awkwardness, I before in the old key file that oneself build new add a part of key, when save again appear error, then just now I directly create a key file paste in, everything is normal, really strange, sorry, disturb you

**Comment by lcq666** [comment]
This software can add a card simulation function is more perfect.

**Comment by ikarus23** [comment]
Thanks for the update. And no, simulating Mifare Classic cards with Android is not possible.
