### ISSUE TITLE
Can't write UID info for Chinese Magic Card gen 1(UID card)

### ISSUE THREAD

**Issue by jixiangyuan** [ikarus23/MifareClassicTool#303]
Hi, I saw that in the "Clone UID" function in the app, it only support UID writing for gen 2 cards, so I was wondering is there any technical issue behind this? Will we be able to write gen 1 cards in future updates? Thank you for your time.

Best regards,
Jack

**Comment by ArchangeGabriel** [comment]
No, because they require sending “backdoor” commands that are not possible on Android.

**Comment by jixiangyuan** [comment]
> No, because they require sending “backdoor” commands that are not possible on Android.

Thank you for your reply. What a pity.
