### ISSUE TITLE
Cloning a 7 byte UID tag to 4 byte UID tag

### ISSUE THREAD

**Issue by Bulte01** [ikarus23/MifareClassicTool#310]
Hello,

I have a card that I need to copy.

The original card has a 7 byte cl2 UID. and the card where I want to copy to has an 4 byte UID.
Is it possible to convert the 4 byte card to an7 byte?

Kind regards

**Comment by longtrung94** [comment]
You need a USB card reader on PC, open notepad and tab this card near card reader, it will show UID on Decimal, convert to Hex 4 byte

**Comment by Bulte01** [comment]
Thanks for the answer! 

I have a usb card reader but when I tab the card near the reader nothing will happens.
With the Mifarewindows tool I can read the card but not convert it.

**Comment by longtrung94** [comment]
![15998977113098243467772721316151](https://user-images.githubusercontent.com/70812966/92990734-ea706780-f508-11ea-98b6-223013876b06.jpg)
Do you have this?

**Comment by Bulte01** [comment]
Not exactly the same but something similar.

![yr](https://user-images.githubusercontent.com/38065858/92990981-baad6980-f4e0-11ea-821b-d16aa2b49049.jpg)

**Comment by longtrung94** [comment]
On my reader, tab the card, beep sound on, notead will show UID 
![20200912_160850](https://user-images.githubusercontent.com/70812966/92992110-7fc42980-f512-11ea-8944-09079a7a976b.jpg)

**Comment by Bulte01** [comment]
> On my reader, tab the card, beep sound on, notead will show UID
> ![20200912_160850](https://user-images.githubusercontent.com/70812966/92992110-7fc42980-f512-11ea-8944-09079a7a976b.jpg)

Ah oke mine does not do that.

But I already know the uid of my cards.

But the original card is 7 bytes and the card where I want to clone to is 4 bytes so i get a bcc error block 0 is not valid

**Comment by longtrung94** [comment]
Give me 10 number UID of your card

**Comment by Bulte01** [comment]
> Give me 10 number UID of your card

04452c5a015580

**Comment by longtrung94** [comment]
Sorry, with your UID "04452c5a015580" I can't help.
I also have 1 card with the same number when read with phone 
![Screenshot_2016-07-06-20-27-14-576x1024](https://user-images.githubusercontent.com/70812966/93001664-dc4b3700-f55a-11ea-8a1c-c1097a06a722.png)
,  but when using my card reader (as picture) it will show 10 numbers in the notepad. then I switch to hex code and write to magic card (finish clone)

**Comment by ikarus23** [comment]
There is a lot of confusion here. So first of:
>Is it possible to convert the 4 byte card to an 7 byte?

No. You need a 7 byte UID changeable card. This has nothing to to with converting hexadecimal to a decimal UID.

There are 7 byte UID cards. Some of them are even compatible with MCT. [This one](https://de.aliexpress.com/item/32830423749.html) might work. These cards can be used to create a perfect clone.
