### ISSUE TITLE
Brute force

### ISSUE THREAD

**Issue by minkov-s** [ikarus23/MifareClassicTool#341]
Hello. Is there a version with the brute force mode? I know that it is slow and inconvenient but i want to try it.

**Comment by ikarus23** [comment]
No, not here. Even trying is not worth it. In most cases you can crack the keys with a $30 RFID USB reader in minutes. This is the way to go. I don't want to be rude but I don't think you fully understand how slow brute force is.
> 48 bit key, 2^48 possible keys (2,814749767×10¹⁴), testing 40 keys/sec
you can have the key in just 81445305 hours, i.e. 223137 years. If the
first homo sapiens started this bruteforce attack now he can get 1 key
of 1 sector.

On a typical 1k card there are 32 keys...
