### ISSUE TITLE
Writer dump error

### ISSUE THREAD

**Issue by yeriis** [ikarus23/MifareClassicTool#343]
What i have ti do if this error appear?(Version 2.3.1)
![IMG_20210326_200649](https://user-images.githubusercontent.com/77756676/112686993-15078980-8e77-11eb-8e59-1c392ded487b.jpg)
P.S:i have tried to use a recente version but it doesnt find me dump.

**Comment by ikarus23** [comment]
First of all: Why use the very old and outdated version?
In more recent versions of MCT, you can import the dumps as described here: https://github.com/ikarus23/MifareClassicTool/issues/326
Now to your question: The dump is not a correct format. Like the error message says, each sector must have 4 lines (blocks) of data. You should check your dump file.

**Comment by ikarus23** [comment]
Any news?

**Comment by ikarus23** [comment]
Closed. Lack of feedback.
