### ISSUE TITLE
Move Motorola One Vision to compatible list

### ISSUE THREAD

**Issue by andreldm** [ikarus23/MifareClassicTool#351]
Hi, I see that this device is in the incompatible list even though I was able to read a Mifare Classic tag with it:

![Screenshot_20210810-220522](https://user-images.githubusercontent.com/599565/128954652-86eb35a9-288c-4062-8e01-a04084455efc.png)

It was blacklisted by 66ee8257, perhaps you meant "Motorola One Vision *Plus*" which is a different device with a different SoC and reported as incompatible device [here](http://www.shopnfc.it/en/content/7-nfc-device-compatibility).

**Comment by ikarus23** [comment]
Thanks for reporting. I will update the list.

**Comment by ikarus23** [comment]
Done. (807416777177c8ce3bc9270a2814022235221ab9)
