### ISSUE TITLE
What does the dash line mean in the reading dump?

### ISSUE THREAD

**Issue by RuralHunter** [ikarus23/MifareClassicTool#355]
Hi,
I just used MCT to read my Mifare card. There are some sectors ending with a block data like this:
------------FF078069FFFFFFFFFFFF
What is the dash lines? No data, not able to read or what else? And what is the possible cause for that? Maybe I missed in the doc but I didn't find anything to explain this.

**Comment by ikarus23** [comment]
Hi. The line (block) you have there is the last block of a sector. Blocks like these are called sector trailer. They store key A, key B, and the access conditions. You need keys to read and write to MIFARE Classic tags. In your example, key B is `FFFFFFFFFFFF`. However, key A is not known. Unknown data is displayed as `------------`.

I hope this helps.
