### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by yesimxev** [ikarus23/MifareClassicTool#357]
I'd like to build this app with a bit of responsive layout for Ticwatch Pro, Pro 3. So need to adapt to screen res 450x450. I can't manage to build it without even touching it in android studio. Can you or anyone who built advise please? Hw compatibility will turn out as soon as the app won't crash on startup

**Comment by ikarus23** [comment]
Hi. Not sure how you trying to build it. For me opening up Android Studio and selecting File->Open->Import Project did always work.

**Comment by yesimxev** [comment]
Just got a reply someone trying to build on Win10 and it worked. I'm building others on Kali and Ubuntu, not sure why this didn't work. Probably libs. Will give it a try

**Comment by ikarus23** [comment]
I'm building it on Arch Linux.

**Comment by ikarus23** [comment]
I will close this for now. Feel free to reopen it, if you have more questions.

**Comment by yesimxev** [comment]
Ah forgot to report back, builds on Win7. Just trying to find out if the nfc chipset is incompatible or just not allowed to be used on the watch. I'll paste the error here if you don't mind. Invalid operation in NFC foreground service or so

**Comment by ikarus23** [comment]
Hmm... not sure about the NFC foreground dispatch system on watches. I guess there could be specifics to the Android ROM.

**Comment by yesimxev** [comment]
Sure, trying to do some research on it. I'm quite new to NFC and (especially) wearOS. Is that needed for only background operation eg. read tag when recognised or even for read with read tag button?

**Comment by ikarus23** [comment]
On an normal Android device the OS handles the detection of NFC tags and informs app when there is a new one. An app can subscribe to this notifications (intents). If you want to have exclusive access to the NFC resource, you need to run in the foreground and register for the foreground dispatch system. https://developer.android.com/guide/topics/connectivity/nfc/advanced-nfc has more information. But I don't think it the same in wearOS

**Comment by yesimxev** [comment]
Awesome! Thank you for the info

**Comment by yesimxev** [comment]
I dug into a little bit, but didn't go far. Is there a chance that the NFC is only capable of sending (eg. Google Pay) on hardware level or maybe just kernel?
