### ISSUE TITLE
MCT not working after update to Android 11 [Cat S62 Pro]

### ISSUE THREAD

**Issue by VASTechAD** [ikarus23/MifareClassicTool#358]
Hello everyone. Just update my Cat S62 pro to Android 11 and MCT not work anymore. It say that this device does not support Mifare Classic. How so, because before A11 was working good. Anyone can help with this issue? Thank You!

**Comment by ikarus23** [comment]
Strange. I guess there must be something wrong with the Android ROM of this device. What error do you get? And when? On app startup or when you trying to read a tag?

**Comment by dorcky** [comment]
Right after i put a card on phone, not even try to read the card. On app startup.

**Comment by ikarus23** [comment]
Could you open the app first (without a card close to your phone)? Is there an error? Or only if you place a card on your phone while the app is running in the foreground?

It probably is the latter. If the error occurs when a card is presented to the open app, then there is nothing I can do (as far as I know). The Android NFC API tells the app that one or both (the phone or the card) does not support MIFARE Classic. It seams like in your case this is a false positive introduced with the new Android version.

**Comment by dorcky** [comment]
Only when i place the card on phone appear that message. The latest Android version is the main problem. It was a mistake to update to 11. Thank`s anyway!

**Comment by ikarus23** [comment]
Another idea: Have you tried other apps to read a MIFARE Classic token? E.g. NFC TagInfo (by NXP). Use it with an empty MIFARE Classic card. This app should also be able to read the content as long as the sectors have default keys.

**Comment by ikarus23** [comment]
Any news?

**Comment by ikarus23** [comment]
Closed. Lack of feedback.
Feel free to reopen this issue if you have new information.
