### ISSUE TITLE
Auto Write Dump (Clone) at the sight of nfc mark

### ISSUE THREAD

**Issue by fairvlad98** [ikarus23/MifareClassicTool#360]
Hi. Can you please tell me, how to implement automatic "Write Dump (Clone)", when you see the nfc mark,  from the last saved dump?

**Comment by ikarus23** [comment]
Hi. Sorry, I have trouble understanding the question. What do you mean by "nfc mark"? Do you want to write back the last saved dump with the same UID once a tag with the same UID is discovered?

**Comment by ikarus23** [comment]
Will close this for now. Feel free to reopen if you have more info.
