### ISSUE TITLE
The keys cannot be edited in version 4.0.2 and above

### ISSUE THREAD

**Issue by MicroDuke** [ikarus23/MifareClassicTool#362]
I  do test the version 4.0.1 & 4.0.2 & 4.0.4.
The version 4.0.1 Can enter after ediiting, The picture is as follows

![image](https://user-images.githubusercontent.com/24806479/146871775-f3bb2eab-34bf-4dca-9153-5b15d5edc653.png)
The version 4.0.2 & 4.0.4 can not enter after editing,The picture is as follows
![image](https://user-images.githubusercontent.com/24806479/146872192-46163020-da2f-463d-a750-2c584c3248e8.png)

This version does not allow screenshots

**Comment by ikarus23** [comment]
Interesting. Did you try the different versions on the same Android device with the same Android version? So far I can not recreate this issue.

**Comment by MicroDuke** [comment]
Yes, both of my phones are xiaomi: mix2 & Mi 11.
Their situation is exactly the same. 
The mix2  Andriod version is 9 ,MIUI is 12.0.1,Kernel is 4.4.153.
The Mi 11 Andriod version is 11 ,MIUI is 12.5.15,Kernel is 5.4.86-qgki. 
I have not tested other phones

**Comment by MicroDuke** [comment]
The keyboard of version 4.02 and above cannot be selected, it is a Xiaomi security keyboard。

**Comment by ikarus23** [comment]
I think I found the issue. Some text fields in this app are declared as `textVisiblePassword`. This is a quick hack to tell keyboards to show an extra row with numbers. This way it is easier to input hex. However, in your case the phone decides to use the "password keyboard", which does not allow the return key.

I guess I have to revert the `textVisiblePassword` definition from all input fields.

**Comment by MicroDuke** [comment]
> I think I found the issue. Some text fields in this app are declared as `textVisiblePassword`. This is a quick hack to tell keyboards to show an extra row with numbers. This way it is easier to input hex. However, in your case the phone decides to use the "password keyboard", which does not allow the return key (as new line).
> 
> I guess I have to revert the `textVisiblePassword` definition from all input fields.

Thanks a lot.
I will test the new release version & report test report.

**Comment by ikarus23** [comment]
I compiled a testing version. Feel free to try it: https://tests.icaria.de/MifareClassicTool-4.0.4-test1.apk

**Comment by MicroDuke** [comment]
> I compiled a testing version. Feel free to try it: https://tests.icaria.de/MifareClassicTool-4.0.4-test1.apk (Edit: fixed link.)

Yes,I do test it .
It is work.
Thanks.

**Comment by ikarus23** [comment]
Thanks for testing. The next version will include the fix.
