### ISSUE TITLE
Can't read key A of sectors 9 [Xiaomi 10 Pro]

### ISSUE THREAD

**Issue by zlqd123** [ikarus23/MifareClassicTool#364]
The key A of sectors 9 read by mct was none. It should be FFFFFFFFFFFF.
![Screenshot_2021-12-31-11-17-21-153_de syss Mifare](https://user-images.githubusercontent.com/32678715/147801531-8e45405f-a135-47f7-be55-7c8e6f44388c.png)

![Screenshot_2021-12-31-11-17-21-153_de syss Mifare](https://user-images.githubusercontent.com/32678715/147801648-e219b869-8b34-4060-baff-00c9755d32eb.png)

MCT 4.0.4 from google play
CUID card
Xiaomi 10pro MIUI13 21.12.27

**Comment by zlqd123** [comment]
The second picture should be this.
![Screenshot_2021-12-31-10-09-10-363_de syss Mifare](https://user-images.githubusercontent.com/32678715/147801726-72408786-0b60-4a8e-84a1-767e24d554cb.png)

**Comment by zlqd123** [comment]
MCT can't write the key A of sectors 9 either.

**Comment by ikarus23** [comment]
It just looks like you don't know key A for this card.

**Comment by zlqd123** [comment]
> 看起来你不知道这张卡的钥匙A。

I've got the full dump file and a key file. It could be read before.
Maybe it's Andriod12.

**Comment by ikarus23** [comment]
Could be. There are other people having issues with Android 12. Please have a look at https://github.com/ikarus23/MifareClassicTool/issues/361#issuecomment-1001992143. It might help you,

**Comment by ikarus23** [comment]
Have you tried one of the solutions?
It seems like more and more people have this issue after updating Android...

**Comment by ikarus23** [comment]
I will close this for now. Feel free to reopen it if you have more information about the topic.
