### ISSUE TITLE
Keys of armenian underground card ticket 

### ISSUE THREAD

**Issue by alximiktik** [ikarus23/MifareClassicTool#365]
E4410EF8ED2D
6A68A7D83E11
0D6057E8133B
D3F3B958B8A3
3E120568A35C
2196FAD8115B
7C469FE86855
A0A1A2A8A4A5
CE99FBC8BD26

**Comment by ikarus23** [comment]
Hi. Thank you. Are the keys the same on every card?

**Comment by alximiktik** [comment]
Yes. Every card have same keys. But i want to warn that soon payment system(nfc ticket-card) will change.

**Comment by ikarus23** [comment]
Ok. I will add the keys, even if the system will change soon. Good for legacy research ;)

**Comment by ikarus23** [comment]
Done with ff42f5596e83f234beafc0b5f1eb2a4f330059e0
