### ISSUE TITLE
App not workinf properly on Galaxy S20 Fe

### ISSUE THREAD

**Issue by Nicholas1501** [ikarus23/MifareClassicTool#388]
When I try to read the card, the message "There is no MIFARE Classic tag shows up.
Android Version: 12
One UI Version: 4.1
Baseband Version: G780GXXS3CVD7

**Comment by ikarus23** [comment]
Hi. Can you confirm it is indeed a MIFARE Classic tag? Can you check the tag using another app like TagInfo by NXP?

**Comment by ikarus23** [comment]
Closed. Lack of feedback. If there any relevant news, feel free to reopen the issue.
