### ISSUE TITLE
Device does (not) support Mifare Classic

### ISSUE THREAD

**Issue by mmm4m5m** [ikarus23/MifareClassicTool#389]
Maybe the message is wrong. Or checking for Mifare Classic support is incorrect.

1. Metrodroid application report that phone have support for Mifare Classic
"You can verify MIFARE Classic support in Metrodroid's about screen."
https://github.com/metrodroid/metrodroid/wiki/Cracking-keys

2. As far I could find and read in the code, my phone do not have 'bcm' or 'bcrm' files:
`$ adb shell find /dev /system | grep -i 'bcm\|bcrm'`

> hasMifareClassicSupport: ...this function will check if there are files like "/dev/bcm2079x-i2c" or "/system/lib/libnfc-bcrm*"

https://github.com/ikarus23/MifareClassicTool/blob/master/Mifare%20Classic%20Tool/app/src/main/java/de/syss/MifareClassicTool/Common.java

![image](https://user-images.githubusercontent.com/995706/174430085-36288b2b-7b58-4b95-bb30-2f5f7d5d5a19.png)

**Comment by ikarus23** [comment]
Hi. Detecting if a device supports MIFARE Classic is hard. Without presenting a MIFARE Classic tag to your device you can not be sure. While I don't think my detection mechanism might be right all the time, I don't think the one of Metrodroid is either. Have you checked other apps like TagInfo by NXP?

**Comment by ikarus23** [comment]
Also, what device are you using?

**Comment by mmm4m5m** [comment]
@ikarus23
Device is OnePlus3T with LineageOS.
I guess the NFC files/drives are vendor specific - not from LineageOS.

I do not know much about NFC (yet).
Is Tag.techList not enough for "yes/no" Mifare support?
Above message (not supported) is shown after tap NFC card.

I am looking mostly at open source examples.
If I find good example I will let you know.
Here from TagInfo by NXP - the same NFC card - city transport card:

![image](https://user-images.githubusercontent.com/995706/175792686-a01fe623-a110-4918-854e-a761ddb74aee.png)

![image](https://user-images.githubusercontent.com/995706/175792716-145eb126-1a6e-4f13-9976-741522b6f6c3.png)

![image](https://user-images.githubusercontent.com/995706/175792722-97f10cec-8231-4302-9e8d-6b30411f8a3f.png)

**Comment by ikarus23** [comment]
> @ikarus23 Device is OnePlus3T with LineageOS. I guess the NFC files/drives are vendor specific - not from LineageOS.

Yes, the drivers in LineageOS often differ from the original ones because of legal issues (licensing)

> I do not know much about NFC (yet). Is Tag.techList not enough for "yes/no" Mifare support? Above message (not supported) is shown after tap NFC card.

It is a simple yes/no list, but it only gets filled with data when a tag is touched. If MIFARE Classic is not in the techList, you don't know why. Could be the device not supporting it or the tag not being MIFARE Classic.

> I am looking mostly at open source examples. If I find good example I will let you know. Here from TagInfo by NXP - the same NFC card - city transport card:

The "Full Scan" tab of NFC TagInfo is the important one. Here you will see data, if the device was capable of reading out your tag.
