### ISSUE TITLE
How to generate valid sector 0 data by the already UID number?

### ISSUE THREAD

**Issue by f2sky** [ikarus23/MifareClassicTool#396]
1、Clone UID function does not work.

2、Try to build a dump file based on the fact that the clone UID function is not available.

As shown in the picture below, only sectors **0-5** of a card are read.

If a UID number is: `AE4CA2C1`, how do I generate valid data for **sector 0 block 0** (i.e. the line of data marked in red in the picture)?

Trying to use the clone UID function, but it always fails.

<img width="400" alt="MIFARE2345235" src="https://user-images.githubusercontent.com/8769077/189487680-9444d1ef-43ca-4358-ac22-bb2c8eb68d51.png">

**Comment by ikarus23** [comment]
Hi! Not sure if I understand correctly. There seem to be a language barrier. 

1) What do you mean by that? Do you mean the "Clone UID" tool? What was the error message? For me it looks like you are using a incompatible tag (only on MFIARE Classic Gen2/CUID tags block 0 can be written by MCT). Have a look at: https://github.com/ikarus23/MifareClassicTool#general-information
2) It looks like your tag is a MIFARE Classic Mini. *Mini* tags only have 5 sectors. You can check using NXPs TagInfo app.

**Comment by f2sky** [comment]
My tags work properly with the "Write Dump(Clone)",but not "Clone UID".
Please see the following screenshots.

<img width="1080" alt="qwongg9geo370eg9eg1" src="https://user-images.githubusercontent.com/8769077/192915522-d263c9e3-6fa8-4bd6-a2de-f50109beaeae.png">

<img width="1080" alt="qwongg9geo370eg9eg2" src="https://user-images.githubusercontent.com/8769077/192915539-1fcf66aa-a915-492c-9d0d-3a823abb71b5.png">

**Comment by ikarus23** [comment]
Yes, like I said, I does look like you are using an incompatible tag. Just like the error message says. You can not write block 0 (the UID) of a normal tag. You need a special tag for that. These tags are often called MIFARE Classic Magic gen2/CUID.

**Comment by ikarus23** [comment]
Closing this for now. If you have more questions about this, feel free to reopen it.
