### ISSUE TITLE
How to simulate a card to a phone with known tag data (root available)？

### ISSUE THREAD

**Issue by f2sky** [ikarus23/MifareClassicTool#404]
This function is very useful when using access cards.

**Comment by ikarus23** [comment]
It is possible to emulate ISO7816-4 based tags with Androids [HCE](https://developer.android.com/guide/topics/connectivity/nfc/hce). But there are restrictions (e.g. UIDs are random). Emulating MIFARE Classic tags is not possible, even with root access. For that you probably need custom NFC chip firmware and drivers (kernel modules). I never seen someone pull it off in an easy & reproducible way.

(Closed. Off-Topic to MCT. Feel free to discuss in the closed issue.)
