### ISSUE TITLE
Write dump file failed

### ISSUE THREAD

**Issue by btwang0512** [ikarus23/MifareClassicTool#412]
[test.zip](https://github.com/ikarus23/MifareClassicTool/files/10810145/test.zip)

**Comment by btwang0512** [comment]
![1677144990087(1)](https://user-images.githubusercontent.com/114456620/220870284-602c10f3-0cea-4f1f-a9ce-8db9fcce20cb.png)

When the fitst digit of block data is  'C', the writing will be failed.

**Comment by ikarus23** [comment]
Strange. Looks perfectly fine to me. Is it only on the `C` change? Are you able to write the dump at all? e.g. without changing anything at all?

**Comment by btwang0512** [comment]
Thanks for your reply. Please see the attached file.Sent from my phone-------- Original message --------From: Gerhard Klostermeier ***@***.***>Date: Sat, Mar 4, 2023, 23:13To: ikarus23/MifareClassicTool ***@***.***>Cc: btwang0512 ***@***.***>, Author ***@***.***>Subject: Re: [ikarus23/MifareClassicTool] Write dump file failed (Issue #412)
Strange. Looks perfectly fine to me. Is it only on the C change? Are you able to write the dump at all? e.g. without changing anything at all?

**Comment by btwang0512** [comment]
Sorry. The attached file is sent failed. I will resend it tomorrow.Sent from my phone-------- Original message --------From: ***@***.***: Sat, Mar 4, 2023, 23:59To: ikarus23/MifareClassicTool ***@***.***>, Gerhard Klostermeier ***@***.***>, ikarus23/MifareClassicTool ***@***.***>Cc: Author ***@***.***>Subject: Re:[ikarus23/MifareClassicTool] Write dump file failed (Issue #412)Thanks for your reply. Please see the attached file.Sent from my phone-------- Original message --------From: Gerhard Klostermeier ***@***.***>Date: Sat, Mar 4, 2023, 23:13To: ikarus23/MifareClassicTool ***@***.***>Cc: btwang0512 ***@***.***>, Author ***@***.***>Subject: Re: [ikarus23/MifareClassicTool] Write dump file failed (Issue #412)
Strange. Looks perfectly fine to me. Is it only on the C change? Are you able to write the dump at all? e.g. without changing anything at all?

**Comment by btwang0512** [comment]
[write-dump.zip](https://github.com/ikarus23/MifareClassicTool/files/10907793/write-dump.zip)

Please see attached video file. If the first Digit of block is 'C', the dump write will be failed.

**Comment by ikarus23** [comment]
There is no file. I get a 404 (not found) error.

**Comment by btwang0512** [comment]
![1](https://user-images.githubusercontent.com/114456620/223615430-0e4ba535-cf09-45d7-bb53-f35ae1134388.png)
![2](https://user-images.githubusercontent.com/114456620/223615461-5437432d-8046-472d-aa83-14aacd1576b2.png)
![3](https://user-images.githubusercontent.com/114456620/223615466-b4f74f2a-1e06-47c1-9445-94503a605372.png)
![4](https://user-images.githubusercontent.com/114456620/223615470-88c90075-cf32-4c08-96cf-bf3f96fefd55.png)

Sorry, the video file cannot be upload successfully. I cut some picture from video.

**Comment by ikarus23** [comment]
Any news? Did you try the test version?

**Comment by ikarus23** [comment]
Ok, I just pushed the ugly fix (https://github.com/ikarus23/MifareClassicTool/commit/ec3f0477ceb665b482ffb3194762dd76d3efcb8f) and hope it will help.
