### ISSUE TITLE
Add some features to diff tool

### ISSUE THREAD

**Issue by deunlee** [ikarus23/MifareClassicTool#414]
I've been using this app for years, and it would be great if a few more features were added to the diff tool.

- Show matching percentage of two selected dumps
- Option to hide same sectors

I can make a PR so let me know if it's okay.

**Comment by ikarus23** [comment]
Hi! Sorry for the late response. Sounds great!

I would suggest just to insert a "Hide identical sectors"-checkbox below the dump chooser buttons (A) and to insert a simple text (e.g. "Difference between dumps: 0%") below the line (in the result area, B).
![unnamed](https://github.com/ikarus23/MifareClassicTool/assets/1389516/a84eea20-4d76-4e43-8d66-f8c315c58aeb)

**Comment by deunlee** [comment]
OK!
I'll prepare the PR.

**Comment by ikarus23** [comment]
Merged. Thanks again!
