### ISSUE TITLE
Unreadable sectors after successfully cloned dump.

### ISSUE THREAD

**Issue by ymoustai** [ikarus23/MifareClassicTool#417]
I've been using MCT to Read / Write Mifare dumps. However I noticed something, I saved a dump of the data contained in the card during some state, I've been using  the card  then re-cloning the dump back to it.
First card after some days I successfully wrote the data to the card with no issue whatsoever, when I tried reading it again it was showing some issues:

Write issues 
Some parts are not writable! Check the WHOLE list below.
Sector: 4
Invalid Access Conditions or dead sector :(
Sector: 8
Invalid Access Conditions or dead sector :(
Sector: 9
Invalid Access Conditions or dead sector :(

I was no longer able to write data in hose sectors.

It happened to me again with another card with the same issue.
The vending machine that reads the card isn't connected to any database /  internet or anything to keep log and compare.
Any help would be appreciated.

**Comment by ikarus23** [comment]
Any news?

**Comment by ikarus23** [comment]
Do you have a Proxmark3 or similar device to recover the keys? Maybe the vending machine just changes the keys?

Anyways, I will close this for now. Feel free to reopen it if you have more information.
