### ISSUE TITLE
Factory Format only sect 0, other error

### ISSUE THREAD

**Issue by baudav** [ikarus23/MifareClassicTool#425]
Hi,
 In read tag, if I set only to read by default sector 0.
When request to Factory Format with all good key.. only sector 0 is formated, all other are in error.
Option to change sector is greyed.

Workarround: I set in read tag option to read all sector by default, factory format work.

![IMG_20230728_185640](https://github.com/ikarus23/MifareClassicTool/assets/10183995/8c3a9e90-6c7d-4d39-b05c-047a3cda70fe)
![IMG_20230728_185610](https://github.com/ikarus23/MifareClassicTool/assets/10183995/770027b8-e37f-404b-aa77-e5a45857fc8d)
![IMG_20230728_185435](https://github.com/ikarus23/MifareClassicTool/assets/10183995/9bcd60f1-5bf1-4de6-ad7d-136e7bb9c381)

**Comment by ikarus23** [comment]
Hi. Good catch! That is a bug. "Factory Format" should ignore this setting. Thank you for reporting.

**Comment by ikarus23** [comment]
Fixed by https://github.com/ikarus23/MifareClassicTool/commit/2ba7366b1e4a239d0b8fca3abe39d6a4b6f54c49.
