### ISSUE TITLE
CI is broken

### ISSUE THREAD

**Issue by ikarus23** [ikarus23/MifareClassicTool#427]
Hi @Goooler! Thanks for providing this Project with a CI. Since I updated gradle (https://github.com/ikarus23/MifareClassicTool/commit/df9cad1f07cc2e73548c1305751679dfa79b8340), the CI complains about "Android Gradle plugin requires Java 17 to run. You are currently using Java 11.". Does the `ubuntu-latest` from the CI do not have Java 17?

**Comment by Goooler** [comment]
Addressing the fix to #428.

**Comment by ikarus23** [comment]
Thank you so much. And damn, you are quick!
