### ISSUE TITLE
authenticateSectorWithKeyA cannot be verified

### ISSUE THREAD

**Issue by xiuzhenguo** [ikarus23/MifareClassicTool#432]
After changing the key of keyA to 0000000000, authenticateSectorWithKeyA cannot be verified. Setting the key of keyA to another key will not cause this situation. How can I solve this problem.

byte[] bytesKey = Common.hex2Bytes("000000000000");
auth = mMFC.authenticateSectorWithKey( mKeyMapStatus, bytesKey)

At this point, the value of auth is false

**Comment by ikarus23** [comment]
Hi. This is an known issue for some devices or Android versions (drivers). Nothing I can do about it in MCT. You can read about it here: https://github.com/ikarus23/MifareClassicTool/issues/66.

I will close this as being somewhat of a duplicate of https://github.com/ikarus23/MifareClassicTool/issues/66.
