### ISSUE TITLE
Some sectors of gen2 tag had been broken after factory format

### ISSUE THREAD

**Issue by alximiktik** [ikarus23/MifareClassicTool#437]
I have gen2 bracelet. Using MCT i can change UID. But there's a issues with factory format. After  factory format of gen2 tag, impossible to read some  sectors info. I have tried use proxmark3 , but couldn't fix it.  
![Screenshot_20231006_011438_MIFARE Classic Tool](https://github.com/ikarus23/MifareClassicTool/assets/53880057/09d85f57-77fe-4268-a197-5334470a72c8)
Is it possible to fix it?

**Comment by alximiktik** [comment]
I could find 3rd sector keys : A 000102030405 B 0A0B0C0D0E0F: 1,2 and 13 sectors key cant find let

**Comment by ikarus23** [comment]
Strange.
> I could find 3rd sector keys : A 000102030405 B 0A0B0C0D0E0F: 1,2 and 13 sectors key cant find let

Do the found keys work? What is the content of the e.g. sector 3? Is it even writable? Maybe the factory format did not work because these sectors are read only?

**Comment by ikarus23** [comment]
Any news?

**Comment by ikarus23** [comment]
I will close this for now. Feel free to reopen this if you have more information and tried all the keys.
