### ISSUE TITLE
Import custom dictionary file size is limited

### ISSUE THREAD

**Issue by DevilHunterXX** [ikarus23/MifareClassicTool#446]
After testing, the upper limit of the size of a single dictionary file is 50kb

I hope the dictionary size can support a larger size

Thanks

**Comment by ikarus23** [comment]
Interesting. I don't remember putting a limit there. But could be. Was there an error message? I mean, at a certain file size it might be the wrong approach anyways. Cracking the keys with an USB NFC reader or a Proxmark is way more efficient. I will have a look regardless.

**Comment by DevilHunterXX** [comment]
> Interesting. I don't remember putting a limit there. But could be. Was there an error message? I mean, at a certain file size it might be the wrong approach anyways. Cracking the keys with an USB NFC reader or a Proxmark is way more efficient. I will have a look regardless.

Error: Some key(s) contain invalid data (not hex)

In fact, I have PN532, ACR122U, and Proxmark3  , and they are indeed faster. However, a single phone is easier to carry around or use for emergencies.

**Comment by ikarus23** [comment]
The error message does not make sens with regard to the issue. Might be a bug or some memory limitations.
Or the error message is right. Are you willing to share the key file? Maybe there is some wrongly formatted data there.

**Comment by ikarus23** [comment]
Any news? Are you willing to share the file?

**Comment by ikarus23** [comment]
Just checked the code. I can not find any upper limit. So I think the error message is right. Your file contains something, that is not correctly formatted.

**Comment by ikarus23** [comment]
Feel free to reopen this issue if you can share the key file. Otherwise it will be hard to tell what the issue is.

**Comment by DevilHunterXX** [comment]
[Uploading key.txt…]()

**Comment by DevilHunterXX** [comment]
[key.txt](https://github.com/ikarus23/MifareClassicTool/files/13780488/key.txt)

**Comment by ikarus23** [comment]
Well, look at the very end of the file! This is not a correct format. The error message was right!
<img width="138" alt="image" src="https://github.com/ikarus23/MifareClassicTool/assets/1389516/fefb74e7-da07-4812-8aa5-cb3689516b0a">

**Comment by DevilHunterXX** [comment]
[key_split00.txt](https://github.com/ikarus23/MifareClassicTool/files/13791371/key_split00.txt)
what about this key file ?
![image](https://github.com/ikarus23/MifareClassicTool/assets/105278029/83b21475-af1e-42f0-8963-6eb4f58f4f48)

**Comment by ikarus23** [comment]
Maybe you have to do some reading on Mifare Classic. A key for a Mifare Classic tag is 6 bytes long. The key is represented as hexadecimal (0-9, a-f). The key file of MCT should only contain keys formatted in that way.

Looking at the file there are two lines which contain invalid data. There is just `*` symbol.
<img width="391" alt="image" src="https://github.com/ikarus23/MifareClassicTool/assets/1389516/adb47568-a213-4acb-a0da-12ad40e9cfe1">
