### ISSUE TITLE
Android 14 support

### ISSUE THREAD

**Issue by jalenzz** [ikarus23/MifareClassicTool#451]
It seems not support Android 14

I uesd version 4.1.0，the read tag and write tag did not work

**Comment by ikarus23** [comment]
Hi. There are users with Android 14 and no issues. So let's dig deeper. What device are you using? Have you tried other apps like NXP's TagInfo?

**Comment by jalenzz** [comment]
I have tried NXP's TagInfo, it can successfully read the data of card.

I user MEIZU 21, Flyme 10.5, Android 14. I record a video


https://github.com/ikarus23/MifareClassicTool/assets/57910033/4cd3bc59-b91b-443f-9c3b-8c8621a98755

**Comment by jalenzz** [comment]
read tag and write tag have this problem

but other functions like clone UID works well

**Comment by ikarus23** [comment]
Hi. Can you try [this testing version](https://tests.icaria.de/MifareClassicTool-4.1.0-test2.apk)? There is a fix for Android 14 in there.

**Comment by jalenzz** [comment]
It works now!
Thanks!
