### ISSUE TITLE
ASCII text to hex converter

### ISSUE THREAD

**Issue by hexadec** [ikarus23/MifareClassicTool#47]
Could you add a menu in the dump editor, which can convert ASCII text to hexadecimal format?
(Eg. A dialog with an edittext, and it copies the converted text to the clipboard, the user needs to paste it only.)
And it's very annoying, that the back button exit immediately (in the key editor too), and there is no question if I really wanted to do that, or a button to go back and save.

(Sorry for my bad English, I hope you can understand it :-) )

**Comment by ikarus23** [comment]
Done as of e199cd670069e5e4e54314fea60999890620fee5. Will be in next release.
