### ISSUE TITLE
Not tag when starting the mapping process

### ISSUE THREAD

**Issue by xcypher78** [ikarus23/MifareClassicTool#474]
new tag found 

when i click "start mapping and read tag"

Error: There is no MIFARE Classic tag

samsung galaxy a22

**Comment by ikarus23** [comment]
Did you try re-taping the tag? So move it away from the phone and place it again on the reader. Sometimes the connection gets lost.

**Comment by ikarus23** [comment]
What information is shown by NXP TagInfo? What version of Android are you using?

**Comment by ikarus23** [comment]
Can you be more specific? Which information was it able to read? Only the UID? More? What was the detected technology? What was the error?

**Comment by ikarus23** [comment]
Any news?
