### ISSUE TITLE
OnePlus 8 "not not mifare classic tag"

### ISSUE THREAD

**Issue by Laranjo1** [ikarus23/MifareClassicTool#475]
Someone know why not read?
![Screenshot_2024-04-13-08-31-53-12_95b7d1e8510fa3032a240bd8b4b39632](https://github.com/ikarus23/MifareClassicTool/assets/91355461/6ce87559-531a-4a01-8000-95cd582bf6b2)

**Comment by ikarus23** [comment]
This app -- "MIFARE Classic Tool" -- can only read/write/interact with MIFARE Classic card. There are many NFC technologies out there. The card/tag you are using is not MIFARE classic. Just press "read more".
