### ISSUE TITLE
Hope to add the ability to simulate NFC cards on the root phone in the future.

### ISSUE THREAD

**Issue by marsgovernor** [ikarus23/MifareClassicTool#483]
This app has this feature.
https://play.google.com/store/apps/details?id=com.yuanwofei.cardemulator.pro

Thank you for creating a great app!

**Comment by ikarus23** [comment]
Hi!

Sorry, but I don't think I will implement something like this. First of all - as far as I know - this app does no real MIFARE Classic emulation. It just can emulate arbitrary UIDs (and not the tag memory). Second, this is very hardware/software specific. I don't have the time to keep track of all the devices out there. Furthermore, this only works on rooted devices. MCT is supposed to run on all devices.

I guess this is a typical case of "there is a tool (app) for everything". MCT is the app for reading/writing/analyzing MIFARE Classic tags. NFC Card Emulator Pro is the app for emulating UIDs using rooted phones.
