### ISSUE TITLE
Could not read error messages

### ISSUE THREAD

**Issue by sgergo** [ikarus23/MifareClassicTool#488]
Hi

I'd like to change the manufacturer ID in some - supposedly - rewriteable block 0 ID cards from [Aliexpress](https://www.aliexpress.com/item/32970546320.html?spm=a2g0o.order_list.order_list_main.5.46951802p3sInl) .

What I tried is to copy sector0/block0 bytes, replaced first 4 bytes to new UID, calculated new BCC, replaced 5th byte and paste the modified block0 data to write block 0 using MCT. Some error messages popped up but I could not read them..are there any background logs in the app? Many thanks!

**Comment by ikarus23** [comment]
Hi, sorry to inform you, you got the wrong type of cards. This is gen1a card. Changing the UID of a gen1a card can not be done with the Android NFC API. What you need are gen2/cuid cards. The same shop sells them: https://www.aliexpress.com/item/32791886990.html. As you can see in the description they mention "android" and "mct" (Mifare Classic Too).
