### ISSUE TITLE
Nfc emulation?

### ISSUE THREAD

**Issue by milindgoel15** [ikarus23/MifareClassicTool#489]
So I am looking for a way to emulate my phone to unlock my door instead of using my normal card. I checked out this app and did get a way to read/write/clone data but couldn't find any option for emulation.

Also, tried looking for other apps like nfc tools but it required root access which I didn't have. Any way to do this with this app?

**Comment by ikarus23** [comment]
Hi. Sorry full MIFARE Classic card emulation is not possible with Android. That is why you don't find any apps for it. [NFC Card Emulator](https://play.google.com/store/apps/details?id=com.yuanwofei.cardemulator.pro) can emulate the UID of a card on some devices, but not more.

That's it. ¯\_(ツ)_/¯
