### ISSUE TITLE
Default payment app (hidden UID collection)

### ISSUE THREAD

**Issue by 7heMech** [ikarus23/MifareClassicTool#498]
Hey, there!

Beforehand, I'm sorry for my ignorance on this matter.

Would it be possible to make the app open the moment you scan an NFC card, I've seen a number of apps which do this.

What I'm trying to achieve is add my card UID to the UID log while the screen is off.

**Comment by ikarus23** [comment]
Hi. The app will automatically open if you present a Mifare Classic tag (or an ISO 14443 tag in general). Not sure if you can make it the default when there are multiple apps registered for handling those kind of tags. I'm also not familiar about reading UIDs when the screen is off.

Anyways, I'm sorry, but I don't think I will look into this. You use case (a hidden UID collector app) is just to far off. Maybe someone is willing to give it a try or you look into it your self.
