### ISSUE TITLE
Launch app even without NFC

### ISSUE THREAD

**Issue by Aminpro** [ikarus23/MifareClassicTool#50]
I've tried to launch the app on my phone which does not NFC. 
Would love to use the features and tools such as the ACL converter since some people are doing projects which are not on the phone. (Arduino, Raspberry Pi etc. )

**Comment by ikarus23** [comment]
Oh, I never thought of that. :)
I will tweak some code so that you can use it in editor only mode, if your device is not NFC enabled. But please keep in mind that you have to install the app using the .apk file. The Google Play store lists the app only for devices with NFC support.

**Comment by ikarus23** [comment]
Done.
See: cb3de3254b7b24da7222fff4eb7ce799455455f5
