### ISSUE TITLE
Samsung Galaxy M11 is compatible

### ISSUE THREAD

**Issue by krnlexception** [ikarus23/MifareClassicTool#502]
Didn't know if I should just modify list myself and do a PR, or open an issue, so I'm doing the second one.
Samsung Galaxy M11 is compatible with Mifare, it readed my tag sucessfully. I'll test with Redmi Note 10 Pro once I get it back but if 9 Pro and 11 Pro work, 10 Pro should too.

**Comment by ikarus23** [comment]
Hi. Thanks for reporting. I will update the list.

**Comment by ikarus23** [comment]
Done in ca11efe.
