### ISSUE TITLE
Host card Emulation

### ISSUE THREAD

**Issue by stilicrafter** [ikarus23/MifareClassicTool#517]
Hey, 
Would it be possible to Implementat host card emulator. Dont clone it to another card, tap the phone to Reader and Finished

**Comment by ikarus23** [comment]
Hi. Sorry, no that is not possible. Host Card Emulation (HCE) does not allow to emulate MIFARE Classic cards. Emulating a card with a specific UID is also not possible via the normal Android NFC API.
