### ISSUE TITLE
Last version 2.0.0 overwrites Dumps and Key File

### ISSUE THREAD

**Issue by ctrc00** [ikarus23/MifareClassicTool#54]
I updated to the last version.
It has erased my dumps and all my key files.

Android 4.4.4

**Comment by ikarus23** [comment]
Wow. For real? As far as I know I haven't changed anything that could triggered this behavior...
Are you sure this isn't some strange file corruption on your external memory?
Is there anybody else with the same issue? I've got no email, forum posts or what so ever.

P.S. I'm sorry for your (file) loss.

**Comment by ikarus23** [comment]
Now, there are about 10,000 people using MCT version 2.0. So far nobody else reported the same issue. I therefore think this behavior is not caused by MCT.
