### ISSUE TITLE
Add support for other Tags / Phones

### ISSUE THREAD

**Issue by sniperle** [ikarus23/MifareClassicTool#56]
It would be great to implement support for other Tags like e.g. Mifare Ultralight or Topas 512. 

And because of this MCT would be able to work on phones that support tags except the Mifare Classic ones, like Nexus 4 or 5 .....

**Comment by ikarus23** [comment]
Hi sniperle,

(taken from http://www.proxmark.org/forum/viewtopic.php?pid=12827#p12827)
>Oh, thats an nice blog post :) And the app looks fine too.  But I think I will not add Mifare Ultralight support the MCT. The differences between these two technologies are just to big. And I like the UNIX philosophy: one program for one task. In other words: MCT for Mifare Classic and MUT (Mifare Ultralight Tool) for Mifare Ultralight.... Somebody should really write an app like that. ;)

Cheers
ikarus
