### ISSUE TITLE
Enable support for Xperia Z2 (D6543)

### ISSUE THREAD

**Issue by DiegoQueiroz** [ikarus23/MifareClassicTool#61]
Currently, it is not possible to install MCT from Play Store due to compatibility issues, but Xperia Z2 is able to read Mifare Classic tags and, therefore, is fully compatible with this application.

I installed the APK on my Xperia Z2 (D6543) and it is working perfectly. So I think it should be enabled in the Play Store.

**Comment by DiegoQueiroz** [comment]
It is important to notice that the Donate Version is already listed as compatible with Xperia Z2.

**Comment by ikarus23** [comment]
Are you sure? Have you verified reading and writing works? A while ago some users reported that MCT does not work on Z2. [This site](http://www.shopnfc.it/en/content/7-nfc-device-compatibility) says so too.

As I can see in the Google Play Developer interface, there are a bunch of Z2 out there. What exact version do you got there?

A list of Z2 devices:
* SonyXperia Z2 Tablet– SGP512
* SonyXperia Z2 Tablet– SGP511
* SonyXperia Z2 Tablet– SGP551
* SonyXperia Z2– D6503
* SonyXperia Z2 Tablet– SO-05F
* SonyXperia Z2– D6502
* SonyXperia Z2a– D6563
* SonyXperia Z2 Tablet– SGP521
* SonyXperia Z2– SO-03F
* SonyXperia Z2– D6543
* SonyXperia Z2 Tablet– SGP561
* SonyXperia Z2 Tablet– SOT21

**Comment by ikarus23** [comment]
Ups, sorry, I overlooked the **D6543** you mentions twice...
I will activate this model in the app store.

**Comment by ikarus23** [comment]
Do you know if any other model of the list support Mifare Classic?

**Comment by DiegoQueiroz** [comment]
Interesting to know. So maybe some Xperia X2 models does not have NXP chips, while some have it.

Just terrible. ;/
