### ISSUE TITLE
Importing mfoc dump

### ISSUE THREAD

**Issue by akmalhisyam** [ikarus23/MifareClassicTool#76]
trying to open dump from mfoc resulting in this error:

"Some sectors don't have 4 or 16 blocks (lines)"

Is MCT dump format documented anywhere?

**Comment by akmalhisyam** [comment]
found the scripts to convert between the dump format

now I feel stupid

**Comment by ikarus23** [comment]
Don't feel stupid! Neither the scripts nor the dump format are documented on any obvious place...

**Comment by xavave** [comment]
hi, if some one is interested, I've made a gui (windows) app to convert mct <--> nfc /mfoc dumps
[https://github.com/xavave/bm-mifare-classic](url)
