### ISSUE TITLE
Marshmallow permissions (with suggestion)

### ISSUE THREAD

**Issue by systemcrash** [ikarus23/MifareClassicTool#78]
It will probably need something like this in MainMenu.java

    private static final int REQUEST_WRITE_STORAGE = 112;

    @Override
    public void onRequestPermissionsResult( int requestCode, @NonNull String[] permissions, @NonNull int[] grantResults) {
        super.onRequestPermissionsResult(requestCode, permissions, grantResults);
        if (requestCode == REQUEST_WRITE_STORAGE) {
            if (grantResults[0] == PackageManager.PERMISSION_GRANTED) {
                //permission granted  start reading
            } else {
                Toast.makeText(this, "No permission to read external storage.", Toast.LENGTH_SHORT).show();
            }
        }
    }

        if (ActivityCompat.checkSelfPermission(MainMenu.this, Manifest.permission.READ_EXTERNAL_STORAGE) !=
                PackageManager.PERMISSION_GRANTED) {
            ActivityCompat.requestPermissions(MainMenu.this, new String[]{Manifest.permission.READ_EXTERNAL_STORAGE},REQUEST_WRITE_STORAGE);
            return;
        }

See
http://stackoverflow.com/questions/33139754/android-6-0-marshmallow-cannot-write-to-sd-card

I got MFCT to start on MM after compiling the above additions in, although it crashed once around:

mEnableNfc.hide();

**Comment by ikarus23** [comment]
Hi systemcrash, thanks for the code snipped. I will look into it as soon as I got my hands on a Android 6.x device. ;)

Also the crash around `mEnableNfc.hide();` should be fixed within the latest release (2.0.6).

**Comment by ikarus23** [comment]
Have a look at https://github.com/ikarus23/MifareClassicTool/pull/80.

**Comment by ikarus23** [comment]
MCT should work on Android 6.x. now (https://github.com/ikarus23/MifareClassicTool/pull/80 was merged).

**Comment by systemcrash** [comment]
Confirmed - works on my MM device.
