### ISSUE TITLE
I write wrong BCC byte

### ISSUE THREAD

**Issue by aleks921** [ikarus23/MifareClassicTool#85]
I write in classic 1k with direct uid changable BCC byte incorrect.
Help me, please, how restore this card ?
With an invalid BCC byte this card does not see my phone with nfc and acr122u.
How restore, please.

**Comment by ikarus23** [comment]
I've never done this. But I think it is not possible to fix cards with a wrong BCC. Have a look at https://github.com/ikarus23/MifareClassicTool/issues/81.

**Comment by aleks921** [comment]
Card with special comand i fixed after bcc byte) How fixed with direct comand i don't know.

**Comment by ikarus23** [comment]
Added in 57ff1a60f43a14130fcf8bc78e8b6c08c4d77258.

**Comment by aleks921** [comment]
How update MCT for me on smartfon. Download from google play or not.

27.05.2016, 18:00, "ikarus" <notifications@github.com>:

**Comment by ikarus23** [comment]
Yes, I will release the new version of MCT on Google Play within the next days.

**Comment by aleks921** [comment]
Ok, what is number will in new version. Wait new version:)

28.05.2016, 13:49, "ikarus" <notifications@github.com>:
