### ISSUE TITLE
read block0

### ISSUE THREAD

**Issue by akingyin1987** [ikarus23/MifareClassicTool#86]
some times i read block0  

The same label read out the data is not the same
amsung J5 mobile phone

I am from Chinese, a little English

**Comment by ikarus23** [comment]
Hi there, I'm not sure if I understand your issue. You read out block 0 multiple times and some times the read out data is different?

**Comment by akingyin1987** [comment]
yes,This problem has occurred in the Samsung J5 and HUAWEI C199

The same Tag, you have been reading occasionally appear, but I only found these two phones

**Comment by ikarus23** [comment]
So maybe you got a tag that is emulating a Mifare Classic tag. Some of these change the UID every time you read them.

**Comment by akingyin1987** [comment]
NO ，That is the problem of mobile phones, HUAWEI mobile phone upgrade did not find this problem

**Comment by ikarus23** [comment]
So the Samsung J5 reads out random data for block 0 and for the Huawei works well with MCT? I have no idea where this behaviour came from...

**Comment by ikarus23** [comment]
Is there there anyone out there that can reproduce this behavior? Is the Samsung J5 known for having issues with MIFARE Classic?

**Comment by systemcrash** [comment]
Your "libnfc" checks should correctly detect whether a device supports MFC via NFC. Some devices might have faulty blobs/stacks which need updating or fixing.

**Comment by ikarus23** [comment]
Lacking feedback. Closed.
