### ISSUE TITLE
Samsung S5 now compatible with mifare classic

### ISSUE THREAD

**Issue by dv44** [ikarus23/MifareClassicTool#88]
Hello,

Just to tell that my samsung S5 (SM-G900F) is now able to read mifare classic tags.
There must have been a recent update in the firmware. It was not compatible a few months ago.
MifareClassicTool works perfectly on it.

Regards.

**Comment by ikarus23** [comment]
Thank you for reporting the good news! I will take the Samsung Galaxy S5 off the incompatibility list and make MCT available through Google Play again.
