### ISSUE TITLE
[FR] add support of MIFARE Ultralight

### ISSUE THREAD

**Issue by ildar** [ikarus23/MifareClassicTool#90]
The [MIFARE Ultralight](https://en.m.wikipedia.org/wiki/MIFARE#MIFARE_Ultralight_and_MIFARE_Ultralight_EV1) tags are very cheap and widespread. So maybe its support would be reasonable. Also the encryption there is used less.
Actually I don't know would that be useful or useless, please hint.
Thanks for the joy playing with NFC tags!

**Comment by ikarus23** [comment]
Hi ildar! Thanks for the feature request. This was actually requested by another guy some time ago. But I think I will not add Mifare Ultralight support the MCT. The differences between these two technologies are just to big. And I like the UNIX philosophy: one program for one task. In other words: MCT for Mifare Classic and MUT (Mifare Ultralight Tool) for Mifare Ultralight.
... Somebody should really write an app like that. ;-)

For now I only know apps like [Mifare++ Ultralight](https://play.google.com/store/apps/details?id=com.samsung.sprc.fileselector) and [NFCuIT](https://play.google.com/store/apps/details?id=org.bughardy.nfcult).
