### ISSUE TITLE
Thank you for the excellent library!

### ISSUE THREAD

**Issue by IvanSyabro** [ikarus23/MifareClassicTool#94]
Hi, I am very grateful to you for this library. It is the only one that knows how to work with the NFС MifareClassik tags. I want to add it to my app, and I will be grateful if you could tell exactly which piece of code is responsible for reading and writing tags

**Comment by ikarus23** [comment]
Hi, you are welcome. The reading/writing part is done in the [MCReader.java](https://github.com/ikarus23/MifareClassicTool/blob/master/Mifare%20Classic%20Tool/app/src/main/java/de/syss/MifareClassicTool/MCReader.java). But it is just a wrapper to make things a little bit easier. You can access Mifare Classic tags with the Android API pretty well.
