### ISSUE TITLE
add disable autostart option when card detected

### ISSUE THREAD

**Issue by treakiandroid** [ikarus23/MifareClassicTool#97]
hi,
could you please add an option to disable autostart when a card is detected? 

thanks

**Comment by ikarus23** [comment]
As far as I know, this is not possible. Have a look at https://github.com/ikarus23/MifareClassicTool/issues/71

**Comment by treakiandroid** [comment]
it should be possible because it is working with mensaguthaben ( https://github.com/jakobwenzel/MensaGuthaben ) maybe you can adapt there code to add an option to disable autostart. thanks

**Comment by ikarus23** [comment]
Hmm, I tried the app, but it did not work for me. Have you tested this successfully?

**Comment by ikarus23** [comment]
Any news on that? Is there anyone that knows a way to do this?

**Comment by ikarus23** [comment]
Lack of feedback. Closed.

**Comment by ikarus23** [comment]
It works since d6eb7d150cc186509718c18abcfe1ba9ddc8f6b2 thanks to @aerizzo. The feature will be included in the next release.
