### ISSUE TITLE
Zenphone 2 z00a

### ISSUE THREAD

**Issue by bruno-oliveira1** [ikarus23/MifareClassicTool#99]
Hi your APP read tag information, but show this message tour device (due to hardware) dowles not support Mifare classic. How to fix it ? Thank you very much

**Comment by ikarus23** [comment]
Hi! Thanks for reporting that the Zenphone 2 z00a is not compatible with MCT.

As you can read in the error message, there is nothing we can do. It seams like this phone has a NFC controller that is not manufactured by NXP and is therefore not able to read/write MIFARE Classic tags.

**Comment by bruno-oliveira1** [comment]
You know if a buy any one nxp RFID reader I can read Mifare Classic tags ? If not why you recommend ? Thank you very much again.

**Comment by ikarus23** [comment]
The ACR122u RFID reader is a very common to read/write Mifare Classic tags. But there are much cheaper ones.
